import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {describe,expect,it} from 'vitest';
import {SimulationService} from '../src/application/service.js';
import {neverSaw,studentProjection} from '../src/application/projections.js';
import {cloneConfig} from '../src/domain/config.js';
import {closeRound,createGame,replayGame,submit} from '../src/domain/engine.js';
import type {Game} from '../src/domain/types.js';
import {MemoryGameRepository,type GameRepository} from '../src/persistence/repository.js';
import {SqliteGameRepository} from '../src/persistence/sqlite.js';
import {roundPayloads} from '../src/web/rounds.js';

const board='doug_board_deck',assessment='readiness_assessment';
const boardLabel='Version 3 of the board deck contained information you never saw.';
const pageLabel='Page nine of the readiness assessment contained information you never saw.';
function payload(game:Game){const round=game.activeRound,p=structuredClone(roundPayloads[round]);if(round===1&&game.teams[0].currentState.evidence.analyst_memo.accessed)p.memo_handling='raised_deiss';if(round===3){(p.constraint_claim as Record<string,unknown>).implication_text='Queue data identifies the constraint.';const metric=((p.artifact as Record<string,unknown>).metricSet as Array<Record<string,unknown>>)[0];Object.assign(metric,{label:'First-pass rate',category:'quality',unit:'percent'});}if(round===6)(p.parameter_set as Record<string,unknown>).rollback_trigger=null;if(round===9)return game.teams[0].currentState.crises.length?{crisis_responses:Object.fromEntries(game.teams[0].currentState.crises.map(c=>[c.id,{containment:'contain_broad',disclosure:'executive_team',rollback:false}]))}:{presented_figure:{figure_type:'defensible_today',figure_usd:5000000,basis_text:'Based on documented baseline and current queue data.'},disclosure_items:[]};return p;}
function harness(repo:GameRepository=new MemoryGameRepository()){const g=createGame({id:'access-history-test',teamNames:['Test'],config:cloneConfig()});repo.create(g);const service=new SimulationService(repo);const current=()=>service.get(g.id);const open=(id:string,detail:{versionId?:string;page?:number}={})=>service.evidence(g.id,'team-1',id,detail);const advance=()=>{service.submit(g.id,'team-1',payload(current()),'test');return service.close(g.id);};const until=(round:number)=>{while(current().activeRound<round)advance();};return {repo,service,current,open,advance,until};}
const evidence=(game:Game,id:string)=>game.teams[0].currentState.evidence[id];

describe('canonical access-history lifecycle',()=>{
 it('records a canonical artifact open without inventing version access',()=>{const h=harness();h.open(board);expect(evidence(h.current(),board)).toMatchObject({accessed:true});expect(evidence(h.current(),board).accessedVersions).toBeUndefined();expect(neverSaw(h.current().teams[0])).toContain(boardLabel);});
 it('records an explicitly opened version',()=>{const h=harness();h.open(board,{versionId:'v3'});expect(evidence(h.current(),board).accessedVersions).toEqual(['v3']);});
 it('records an explicitly reached page',()=>{const h=harness();h.until(7);h.open(assessment,{page:9});expect(evidence(h.current(),assessment).accessedPages).toEqual([9]);});
 it('retains accessed and discovered flags on round close',()=>{const h=harness();h.open(board);const old=evidence(h.current(),board);h.advance();expect(evidence(h.current(),board)).toMatchObject({accessed:old.accessed,discovered:old.discovered});});
 it('retains version order and content on round close without aliasing',()=>{const h=harness();h.open(board,{versionId:'v3'});h.open(board,{versionId:'v4'});const old=evidence(h.current(),board);h.advance();expect(evidence(h.current(),board).accessedVersions).toEqual(['v3','v4']);expect(evidence(h.current(),board).accessedVersions).not.toBe(old.accessedVersions);});
 it('retains page order and content on round close without aliasing',()=>{const h=harness();h.until(7);for(const page of [1,9,10])h.open(assessment,{page});const old=evidence(h.current(),assessment);h.advance();expect(evidence(h.current(),assessment).accessedPages).toEqual([1,9,10]);expect(evidence(h.current(),assessment).accessedPages).not.toBe(old.accessedPages);});
 it('retains the same version history at every later round and completion',()=>{const h=harness();h.open(board,{versionId:'v3'});const original=structuredClone(evidence(h.current(),board));for(let round=1;round<=10;round++){h.advance();expect(evidence(h.current(),board)).toEqual(original);}expect(h.current().status).toBe('completed');});
 it('retains page history through R7, R8, R9 and R10 closure',()=>{const h=harness();h.until(7);h.open(assessment,{page:9});const original=structuredClone(evidence(h.current(),assessment));for(let round=7;round<=10;round++){h.advance();expect(evidence(h.current(),assessment)).toEqual(original);}});
 it('keeps genuinely opened v3 and Page 9 out of completed Panel 3',()=>{const h=harness();h.open(board,{versionId:'v3'});h.until(7);h.open(assessment,{page:9});h.until(10);h.advance();const items=studentProjection(h.current(),'team-1').debrief!.panels[2].items;expect(items).not.toContain(boardLabel);expect(items).not.toContain(pageLabel);});
 it('does not infer version or page access from generic opens or release',()=>{const h=harness();h.open(board,{versionId:'v4'});h.until(7);h.open(assessment,{page:1});h.until(10);h.advance();expect(neverSaw(h.current().teams[0])).toEqual(expect.arrayContaining([boardLabel,pageLabel]));});
it('does not release inaccessible artifacts or mark unopened artifacts accessed',()=>{const h=harness();expect(()=>h.open(assessment,{page:9})).toThrow('Evidence unavailable');h.open(board,{versionId:'v3'});h.advance();expect(evidence(h.current(),assessment)).toMatchObject({available:false,accessed:false});expect(evidence(h.current(),'article_14').accessed).toBe(false);expect(h.current().teams[0].artifacts.some(a=>a.id===assessment)).toBe(false);});
 it('keeps dynamic Round 3 Analysis on its existing whole-record path',()=>{const h=harness();h.until(4);const id=h.current().teams[0].artifacts.find(a=>a.type==='round3_analysis')!.id;h.open(id);const old=structuredClone(evidence(h.current(),id));h.until(10);h.advance();expect(evidence(h.current(),id)).toEqual(old);expect(studentProjection(h.current(),'team-1').artifacts.find(a=>a.id===id)).toHaveProperty('content');});
 it('preserves independent access during explicit game replay',()=>{const h=harness();h.open(board,{versionId:'v3'});h.until(7);h.open(assessment,{page:9});h.open('analyst_memo');const old=h.current(),replayed=replayGame(old);for(const id of [board,assessment,'analyst_memo'])expect(evidence(replayed,id)).toEqual(evidence(old,id));expect(replayGame(replayed)).toEqual(replayed);expect(replayed.teams[0].results).toEqual(old.teams[0].results);});
 it('keeps generated access during explicit game replay',()=>{const h=harness();h.until(4);const id=h.current().teams[0].artifacts.find(a=>a.type==='round3_analysis')!.id;h.open(id);expect(evidence(replayGame(h.current()),id)).toEqual(evidence(h.current(),id));});
 it.each(['analyst_memo','ferrara_cheat_sheet','boyce_database','stale_weekend_feed'])('preserves Panel 3 evidence flag %s through completion and replay',id=>{const h=harness();h.until(2);h.open(id);h.until(10);h.advance();expect(evidence(h.current(),id).accessed).toBe(true);expect(evidence(replayGame(h.current()),id).accessed).toBe(true);const labels:Record<string,string>={analyst_memo:'The Reyes memo contained information you never saw.',ferrara_cheat_sheet:'Marisol had information she never shared with you.',boyce_database:'Tyrell had information he never shared with you.',stale_weekend_feed:'Kubiak had information he never shared with you.'};expect(neverSaw(h.current().teams[0])).not.toContain(labels[id]);});
 it('leaves numerical results, narratives and all non-evidence state unchanged',()=>{const h=harness();const before=h.current();h.open(board,{versionId:'v3'});const p=payload(before),control=closeRound(submit(before,'team-1',p)),opened=closeRound(submit(h.current(),'team-1',p));expect(opened.teams[0].results).toEqual(control.teams[0].results);expect(opened.teams[0].roundNarratives).toEqual(control.teams[0].roundNarratives);const {evidence:_a,...a}=opened.teams[0].currentState,{evidence:_b,...b}=control.teams[0].currentState;expect(a).toEqual(b);expect(_a[board].accessedVersions).toEqual(['v3']);expect(_b[board].accessedVersions).toBeUndefined();});
 it('keeps student projections free of new access internals and hidden metadata',()=>{const h=harness();h.open(board,{versionId:'v3'});h.advance();const view=JSON.stringify(studentProjection(h.current(),'team-1'));for(const key of ['accessedVersions','accessedPages','hiddenMetadata','hiddenScores','rationale_tags','weighted_score','ruleTraces'])expect(view).not.toContain(`"${key}"`);expect(view).toContain('"selectedVersion":"v3"');});
 it('persists full H through SQLite reload, later closes, completion and explicit replay',()=>{const dir=mkdtempSync(join(tmpdir(),'bpm-access-history-')),path=join(dir,'isolated.sqlite');let repo=new SqliteGameRepository(path);try{const h=harness(repo);h.open(board,{versionId:'v3'});h.advance();h.until(7);h.open(assessment,{page:9});h.open('analyst_memo');const id=h.current().teams[0].artifacts.find(a=>a.type==='round3_analysis')!.id;h.open(id);const expected=Object.fromEntries([board,assessment,'analyst_memo',id].map(key=>[key,structuredClone(evidence(h.current(),key))]));repo.close();repo=new SqliteGameRepository(path);let service=new SimulationService(repo);for(let round=7;round<=10;round++){const g=service.get('access-history-test');service.submit(g.id,'team-1',payload(g),'test');service.close(g.id);}const complete=service.get('access-history-test');repo.save(replayGame(complete));repo.close();repo=new SqliteGameRepository(path);service=new SimulationService(repo);const loaded=service.get('access-history-test');expect(loaded.status).toBe('completed');for(const [key,value]of Object.entries(expected))expect(evidence(loaded,key)).toEqual(value);expect(evidence(loaded,'article_14').accessed).toBe(false);const items=studentProjection(loaded,'team-1').debrief!.panels[2].items;expect(items).not.toContain(boardLabel);expect(items).not.toContain(pageLabel);expect(items).toContain('Tyrell had information he never shared with you.');}finally{repo.close();rmSync(dir,{recursive:true,force:true});}});
 it('keeps opened and unopened Panel 3 artifacts distinct after close and SQLite reload',()=>{const dir=mkdtempSync(join(tmpdir(),'bpm-access-negative-')),path=join(dir,'isolated.sqlite');let repo=new SqliteGameRepository(path);try{const h=harness(repo);h.open(board,{versionId:'v3'});h.until(10);h.advance();repo.close();repo=new SqliteGameRepository(path);const g=repo.get('access-history-test')!;expect(evidence(g,board).accessed).toBe(true);expect(evidence(g,assessment).accessed).toBe(false);expect(neverSaw(g.teams[0])).not.toContain(boardLabel);expect(neverSaw(g.teams[0])).toContain(pageLabel);}finally{repo.close();rmSync(dir,{recursive:true,force:true});}});
});
