import {describe,expect,it} from 'vitest';import {cloneConfig,configHash} from '../src/domain/config.js';import {calculateRisks,computeBenefitPipeline,computeReadiness,crisisDamage,determineOutcome,implicationScore,initialState,scoreAdvisors,selectCrises,severityFactor} from '../src/domain/engine.js';import {attentionCost,isSemanticNull,submissionSchema} from '../src/domain/schemas.js';import type {RoundNumber,RoundSubmission} from '../src/domain/types.js';
const c=cloneConfig();const sub=(round:RoundNumber,payload:Record<string,unknown>):RoundSubmission=>({id:`s${round}`,gameId:'g',teamId:'t',round,payload,submitter:'x',submittedAt:'2026-01-01T00:00:00Z',configVersion:'bpm-v1',configHash:configHash(c)});const artifact={bottleneckMap:{stations:[{station:'authorization',input:100,capacity:91,output:91}]},metricSet:[{id:'first-pass',label:'First pass',category:'quality',unit:'percent',baselineValue:70,targetValue:90}]};
describe('ratified calibration',()=>{
 it('has seven canonical stations without charge capture',()=>expect(c.stations).toEqual(['scheduling','registration','verification','authorization','financial_clearance','claim_submission','denial_management']));
 it.each([['denials_only',1.15,.45],['denials_through_auth',1,.72],['full_front_end',.85,1]] as const)('calibrates %s discovery scope',(id,m,coverage)=>{expect(c.discovery.scopeMultipliers[id]).toBe(m);expect(c.discovery.scopeCoverage[id]).toBe(coverage)});
 it.each([['location',.3],['arithmetic',.25],['implication',.45]] as const)('calibrates constraint %s weight',(k,v)=>expect(c.claimScoring.constraintWeights[k]).toBe(v));
 it.each([['pilot_single_site',28],['phase_by_function',42],['system_wide',14]] as const)('calibrates %s duration',(k,v)=>expect(c.durations[k]).toBe(v));
 it.each([['command_center',240000],['parallel_running',400000],['manual_fallback',160000],['rollback_capability',320000]] as const)('prices %s',(k,v)=>expect(c.budget.controlCosts[k]).toBe(v));
 it('prices the complete R8 cutover-control package at $1,120,000',()=>expect(Object.values(c.budget.controlCosts).reduce((sum,value)=>sum+value,0)).toBe(1120000));
 it.each([['named_process_owner',180000],['monitoring_metrics',120000],['exception_review_cadence',90000],['change_governance',160000]] as const)('prices %s',(k,v)=>expect(c.budget.sustainmentCosts[k]).toBe(v));
 it.each([[0,.55],[1,.68],[2,.8],[3,.91],[4,1]] as const)('retains benefit for %s sustainment items',(n,v)=>expect(c.benefits.sustainmentRetention[n]).toBe(v));
 it.each([['A',.3],['B',.7],['C',1],['D',1.2]] as const)('has %s automation multiplier',(k,v)=>expect(c.automationMultipliers[k]).toBe(v));
 it.each([['let_run',0],['contain_narrow',25],['contain_broad',55],['halt_process',70]] as const)('prices containment %s',(k,v)=>expect(c.attention.containment[k]).toBe(v));
 it.each([['none',0],['okonkwo_only',5],['executive_team',10],['board_proactive',20],['public',30]] as const)('prices disclosure %s',(k,v)=>expect(c.attention.disclosure[k]).toBe(v));
 it('has no unresolved content after the supplied Reyes voice brief',()=>expect(Object.keys(c.unresolved)).toEqual([]));
});
describe('claims and discovery',()=>{
 it.each([[91,1],[86,1],[96,1],[81,.75],[101,.75],[71,.4],[111,.4],[70,0],[112,0]] as const)('scores arithmetic boundary %s',(value,score)=>{const parsed=submissionSchema(3,c).parse({constraint_claim:{station:'authorization',shortfall_estimate:value,implication_text:'Verification was upstream and automation moved pressure to the bottleneck'},published_baseline:'defer',artifact});expect(parsed).toBeTruthy();const d=Math.abs(value-91),actual=d<=5?1:d<=10?.75:d<=20?.4:0;expect(actual).toBe(score)});
 it.each([['Verification sits upstream; automation shifted pressure to the authorization queue.',1],['Automating verification increased throughput and moved the bottleneck rather than removing it.',.45],['Verification is before the constraint and the faster automated flow increased pressure.',1],['Verification was upstream.',.45],['The queue became a bottleneck after automation.',.45],['Nothing relevant happened.',0]] as const)('semantic implication paraphrase',(text,score)=>expect(implicationScore(text)).toBe(score));
 it('distinguishes concentrated depth from system understanding',()=>{const raw=20;expect(raw*c.discovery.scopeMultipliers.denials_only).toBeGreaterThan(raw*c.discovery.scopeMultipliers.full_front_end);expect(raw*c.discovery.scopeMultipliers.denials_only*c.discovery.scopeCoverage.denials_only).toBeLessThan(raw*c.discovery.scopeMultipliers.full_front_end*c.discovery.scopeCoverage.full_front_end)});
});
describe('readiness and benefit',()=>{
 it.each([[0,.6],[25,.7],[50,.8],[75,.9],[100,1]] as const)('interpolates discovery %s',(discovery,m)=>{const base=15+30+20+25;expect(computeReadiness({designQuality:100,executorPosition:100,frontline:true,trainingUsd:700000,discoveryDepth:discovery},c)).toBeCloseTo(base*m)});
 it.each([[0,0],[350000,50],[700000,100],[1400000,100]] as const)('normalizes training %s',(usd,normalized)=>{const r=computeReadiness({designQuality:0,executorPosition:0,frontline:false,trainingUsd:usd,discoveryDepth:100},c);expect(r).toBeCloseTo(normalized*.25)});
 it.each([[40,.35],[70,.675],[100,1]] as const)('scales crisis severity %s',(severity,f)=>expect(severityFactor(severity)).toBeCloseTo(f));
 it.each([['restate_documented',1],['publish_range',.92],['defer',.8],['adopt_inherited',.53]] as const)('applies %s credibility method',(baseline,modifier)=>{const p=computeBenefitPipeline({ambition:'clean_sheet',depth:'D',readiness:100,crises:[],sustainmentCount:4,financialCredibility:100,boardCredibility:100,baseline},c)!;expect(p.defensible/p.realized).toBeCloseTo(modifier)});
 it('makes adopt-inherited Triumph arithmetic unreachable',()=>{const p=computeBenefitPipeline({ambition:'clean_sheet',depth:'D',readiness:100,crises:[],sustainmentCount:4,financialCredibility:100,boardCredibility:100,baseline:'adopt_inherited'},c)!;expect(p.realized).toBe(15000000);expect(p.defensible).toBe(7950000);expect(determineOutcome({defensible:p.defensible,realized:p.realized,crises:[],publicCrisis:false,sustainment:['named_process_owner','monitoring_metrics','exception_review_cadence','change_governance'],boardCredibility:100,positiveRelationships:9,damagedRelationships:0,executiveIntervention:false},c)).not.toBe('triumph')});
 it('requires actual containment for a low crisis',()=>expect(determineOutcome({defensible:9000000,realized:9000000,crises:[{severity:45,fullyContained:false}],publicCrisis:false,sustainment:['named_process_owner','monitoring_metrics','exception_review_cadence'],boardCredibility:80,positiveRelationships:7,damagedRelationships:0,executiveIntervention:false},c)).not.toBe('triumph'));
});
describe('risk, response, and advisors',()=>{
 it.each([[60,0],[59,5],[45,5],[44,10],[30,10],[29,15]] as const)('financial credibility %s contributes %s',(cred,points)=>{const decisions=[sub(6,{automation_depth:'A',automates_authorization:false,sourcing:'retain_internal',parameter_set:{threshold_usd:1,threshold_owner:'x',change_detection:'x',queue_owner_and_authority:'x',rollback_trigger:{threshold:1,authority:'x'},patient_escalation_path:'x'}}),sub(8,{go_decision:true,cutover_controls:[]})];const s=initialState(c);s.scalars.financial_credibility=cred;expect(calculateRisks(decisions,s,c).duplicate_posting.contributions.find(x=>x.sourceRule==='financial_credibility')?.points??0).toBe(points)});
 it.each([['A',0],['B',5],['C',10],['D',15]] as const)('authorization depth %s adds %s',(depth,points)=>{const decisions=[sub(6,{automation_depth:depth,automates_authorization:true,sourcing:'retain_internal',parameter_set:{threshold_usd:1,threshold_owner:'x',change_detection:'x',queue_owner_and_authority:'x',rollback_trigger:{threshold:1,authority:'x'},patient_escalation_path:'x'}})];expect(calculateRisks(decisions,initialState(c),c).silent_field_change.contributions.find(x=>x.sourceRule==='authorization_automation')?.points??0).toBe(points)});
 it.each([['retain_internal',0],['cosource_denials',35],['full_bpo',52.5]] as const)('sourcing %s scales vendor risk',(sourcing,points)=>{const decisions=[sub(6,{automation_depth:'B',automates_authorization:false,sourcing,parameter_set:{}})];expect(calculateRisks(decisions,initialState(c),c).vendor_cliff.contributions.find(x=>x.sourceRule==='transition_governance_absent')?.points??0).toBe(points)});
 it('rejects attention over 100',()=>expect(submissionSchema(9,c,{crisisIds:['a','b'],rollbackFunded:false}).safeParse({crisis_responses:{a:{containment:'contain_broad',disclosure:'public',rollback:true},b:{containment:'contain_broad',disclosure:'public',rollback:true}}}).success).toBe(false));
 it('calculates visible attention exactly',()=>expect(attentionCost({a:{containment:'contain_broad',disclosure:'board_proactive',rollback:true}},true,c)).toBe(95));
 it.each([['let_run',1.2],['contain_narrow',.9],['contain_broad',.65],['halt_process',.5]] as const)('containment %s modifies damage',(containment,m)=>expect(crisisDamage('restatement',100,{containment,disclosure:'none',rollback:false},false,c).factor).toBeCloseTo(m));
 it.each([39,40,59,60] as const)('selection boundary %s remains deterministic',(value)=>{const r=initialState(c).risks;r.statement_4_17.exposure=value;r.duplicate_posting.exposure=value;expect(selectCrises(r,c).length).toBe(value<40?0:value<60?1:2)});
 it('advisor stances use the three-value Phase 2 contract',()=>{const stances=scoreAdvisors(6,{automation_depth:'D',parameter_set:{}},initialState(c),[],c);expect(stances.every(x=>['support','mixed','oppose'].includes(x.valence))).toBe(true)});
 it.each(['TBD','unknown','later','n/a','none',' '] as const)('recognizes semantic null %s',value=>expect(isSemanticNull(value)).toBe(true));
});
