import {describe,expect,it} from 'vitest';import {studentProjection} from '../src/application/projections.js';import {cloneConfig} from '../src/domain/config.js';import {DeterministicConversationProvider} from '../src/domain/conversations.js';import {calculateRisks,closeRound,commitmentGapContribution,createGame,initialState,replayGame,submit,supportedCommitmentUsd} from '../src/domain/engine.js';import type {RoundNumber,RoundSubmission} from '../src/domain/types.js';
const c=cloneConfig();const artifact={bottleneckMap:{stations:[{station:'authorization',input:100,capacity:91,output:91}]},metricSet:[{id:'quality',label:'Quality',category:'quality',unit:'percent'}]};const r3={constraint_claim:{station:'authorization',shortfall_estimate:91,implication_text:'Verification was upstream and automation shifted pressure to the authorization bottleneck.'},published_baseline:'restate_documented',artifact};
describe('commitment-gap acceptance',()=>{
 it('uses the configured $12M full-scale span',()=>expect(c.risks.restatement.commitmentGapFullScaleUsd).toBe(12000000));
 it('returns zero when no commitment was made',()=>expect(commitmentGapContribution(false,20000000,8000000,c)).toBe(0));
 it('returns zero below support',()=>expect(commitmentGapContribution(true,7000000,8000000,c)).toBe(0));
 it('returns zero exactly at support',()=>expect(commitmentGapContribution(true,8000000,8000000,c)).toBe(0));
 it('normalizes a $2M gap to 3.333...',()=>expect(commitmentGapContribution(true,10000000,8000000,c)).toBeCloseTo(10/3));
 it('normalizes a $6M gap to 10',()=>expect(commitmentGapContribution(true,14000000,8000000,c)).toBe(10));
 it('caps a very large gap at 20',()=>expect(commitmentGapContribution(true,30000000,8000000,c)).toBe(20));
 it('derives support from the configured benefit cell and R3 analytical arithmetic',()=>{const subs=[submission(3,r3)];expect(supportedCommitmentUsd(subs,c)).toBe(c.benefits.baseMatrix.redesign_structure_intact.B)});
 it('records a deterministic restatement contribution on replay',()=>{const subs=[submission(1,{opening_posture:'pause_pilot',savings_commitment_made:true,savings_commitment_usd:14500000,memo_handling:'raised_deiss'}),submission(3,r3)];const a=calculateRisks(subs,initialState(c),c).restatement.contributions.find(x=>x.sourceRule==='commitment_gap')!;const b=calculateRisks(subs,initialState(c),c).restatement.contributions.find(x=>x.sourceRule==='commitment_gap')!;expect(a).toEqual(b);expect(a.points).toBe(10)});
});
describe('final regression audits',()=>{
 it('keeps the captured config snapshot authoritative after the source config changes',()=>{const source=cloneConfig();let game=createGame({id:'snapshot',teamNames:['T'],config:source,createdAt:'2026-01-01T00:00:00Z'});game=submit(game,'team-1',{opening_posture:'pause_pilot',savings_commitment_made:false,savings_commitment_usd:null,memo_handling:'raised_deiss'});game=closeRound(game);game=submit(game,'team-1',{discovery_allocation:{document_analysis:25,structured_interviews:25,process_mining:25,floor_observation:25},discovery_scope:'full_front_end'});game=closeRound(game);game=submit(game,'team-1',r3);game=closeRound(game);const before=replayGame(game);source.discovery.scopeMultipliers.full_front_end=99;source.claimScoring.constraintWeights.implication=0;const after=replayGame(game);expect(after.configHash).toBe(before.configHash);expect(after.teams[0].currentState).toEqual(before.teams[0].currentState);expect(after.teams[0].results).toEqual(before.teams[0].results)});
 it.each([1,2,3,4,5,6,7,8,9,10] as RoundNumber[])('student projection round %s excludes internal-only keys',round=>{const game=createGame({teamNames:['T'],config:cloneConfig()});game.activeRound=round;game.teams[0].currentState.scalars.readiness=88;game.teams[0].currentState.risks.restatement.exposure=77;const json=JSON.stringify(studentProjection(game,'team-1'));for(const secret of ['exposure','hiddenScores','constraint_claim','readiness','credibilityFactor','baselineMethodModifier','sourceRule','contributions','selection'])expect(json).not.toContain(secret)});
 it('renders the no-crisis state as a benefit-review decision context',()=>{const game=createGame({teamNames:['T'],config:cloneConfig()});game.activeRound=9;const view=studentProjection(game,'team-1');expect(view.decision.crisisInstances).toEqual([]);expect(view.situation).toContain('Crisis response or benefit review')});
 it.each(['marchetti','oyelaran','castellanos','brennan','kowalczyk','okonkwo'] as const)('%s deterministic prose contains no prohibited instruction',async advisor=>{const reply=await new DeterministicConversationProvider().reply({gameId:'g',teamId:'t',round:6,actorType:'advisor',actorId:advisor,message:'help',state:initialState(c)});expect(reply.toLowerCase()).not.toMatch(/correct answer|right answer|option [a-d] is|will cause|risk score|hammer|kotter|crisis .*fire/)});
});
function submission(round:RoundNumber,payload:Record<string,unknown>):RoundSubmission{return {id:`s${round}`,gameId:'g',teamId:'t',round,payload,submitter:'test',submittedAt:'2026-01-01T00:00:00Z',configVersion:'bpm-v1',configHash:'test'};}
