import {describe,expect,it} from 'vitest';import {cloneConfig} from '../src/domain/config.js';import {closeRound,createGame,submit} from '../src/domain/engine.js';
const metric={id:'first-pass-clean',label:'First-pass clean rate',category:'quality',unit:'percent',baselineValue:62,targetValue:88};const artifact={bottleneckMap:{stations:[{station:'verification',input:118,capacity:110,output:108},{station:'authorization',input:108,capacity:91,output:91}]},metricSet:[metric]};
const base=[
 {opening_posture:'pause_pilot',savings_commitment_made:false,savings_commitment_usd:null,memo_handling:'raised_deiss'},
 {discovery_allocation:{document_analysis:5,structured_interviews:25,process_mining:30,floor_observation:40},discovery_scope:'full_front_end'},
 {constraint_claim:{station:'authorization',shortfall_estimate:91,implication_text:'Verification is upstream; automation moved pressure into the authorization bottleneck rather than removing it.'},published_baseline:'restate_documented',artifact},
 {root_cause_claim:{primary_component:'eligibility_front_end_data',secondary_component:'authorization_workflow',weights:[34,27],framing:'system_condition'}},
 {redesign_ambition:'clean_sheet',design_room:['frontline_staff','union','physicians','it'],process_ownership:'ntende'},
 {automation_depth:'D',automates_authorization:false,sourcing:'retain_internal',parameter_set:{threshold_usd:1000,threshold_owner:'CFO',change_detection:'Version monitor',queue_owner_and_authority:'Revenue cycle director may halt',rollback_trigger:{threshold:10,authority:'CIO'},patient_escalation_path:'Patient advocate'}},
 {implementation_approach:'phase_by_function',coalition_actions:['anand_concrete_commitment','walters_negotiated_path','moreau_advance_brief','ntende_public_ownership'],budget_allocation:{training:700000,contingency_reserve:2100000}},
 {go_decision:true,cutover_controls:['command_center','parallel_running','manual_fallback','rollback_capability']}
] as Array<Record<string,unknown>>;
function run(overrides:Record<number,Record<string,unknown>>={},response='strong'){let g=createGame({id:'golden',teamNames:['Team'],config:cloneConfig(),createdAt:'2026-09-02T00:00:00Z'});for(let round=1;round<=8;round++){g=submit(g,'team-1',overrides[round]??base[round-1],'fixture',`2026-09-${String(round).padStart(2,'0')}T00:00:00Z`);g=closeRound(g);}const responses=Object.fromEntries(g.teams[0].currentState.crises.map(x=>[x.id,response==='strong'?{containment:'contain_broad',disclosure:'executive_team',rollback:['duplicate_posting','silent_field_change'].includes(x.id)}:{containment:'let_run',disclosure:'none',rollback:false}])),r9=g.teams[0].currentState.crises.length?{crisis_responses:responses}:{presented_figure:{figure_type:'range_with_assumptions',figure_usd:8000000,basis_text:'Nine days of queue data compared with the documented baseline period and current cost-to-collect source.'},disclosure_items:['nine_days_of_data','queue_stopped_growing_not_shrinking','cost_to_collect_lags_two_quarters','denial_rate_still_noisy']};g=submit(g,'team-1',r9,'fixture','2026-09-09T00:00:00Z');g=closeRound(g);g=submit(g,'team-1',overrides[10]??{sustainment:['named_process_owner','monitoring_metrics','exception_review_cadence','change_governance'],metric_strategy:'inherit',board_narrative:{claimed_benefit_usd:8000000,disclosure_items:['assumptions_stated','two_quarter_lag']}},'fixture','2026-09-10T00:00:00Z');return closeRound(g);}
describe('golden R1-R10 walkthroughs',()=>{
 it('golden_no_crisis keeps every eligible exposure below 40 and reaches benefit review',()=>{const g=run(),t=g.teams[0],eligible=Object.values(t.currentState.risks).filter(x=>x.eligible),r9=t.results.find(x=>x.round===9)!;expect(Math.max(...eligible.map(x=>x.exposure))).toBeLessThan(40);expect(t.currentState.crises).toHaveLength(0);expect(r9.derived.scenario).toBe('benefit_review');});
 it('golden_triumph reaches Triumph through normal R1-R10 submissions',()=>{const g=run(),t=g.teams[0];expect(g.status).toBe('completed');expect(t.currentState.scalars.defensible_benefit_usd).toBeGreaterThan(8000000);expect(t.currentState.crises).toHaveLength(0);expect(t.currentState.scalars.board_credibility).toBeGreaterThanOrEqual(60);expect(t.currentState.outcome).toBe('triumph');expect(t.currentState.budget.ledger.map(x=>x.item)).toEqual(expect.arrayContaining(['training','command_center','monitoring_metrics','named_process_owner']));});
 it('charges the authoritative R8 prices and preserves the disciplined ledger',()=>{const ledger=run().teams[0].currentState.budget.ledger,controls=ledger.filter(x=>['command_center','parallel_running','manual_fallback','rollback_capability'].includes(x.item));expect(ledger.find(x=>x.item==='training')?.remainingBalance).toBe(2100000);expect(controls.map(x=>[x.item,x.amount])).toEqual([['command_center',240000],['parallel_running',400000],['manual_fallback',160000],['rollback_capability',320000]]);expect(controls.reduce((sum,x)=>sum+x.amount,0)).toBe(1120000);expect(controls.at(-1)?.remainingBalance).toBe(980000);expect(ledger.at(-1)?.remainingBalance).toBe(430000);});
 it('places an above-$8M one-crisis path that misses Triumph in win-with-scars',()=>{const g=run({5:{redesign_ambition:'clean_sheet',design_room:['frontline_staff','union','physicians'],process_ownership:'ntende'}}),t=g.teams[0];expect(t.currentState.crises).toHaveLength(1);expect(t.currentState.crises[0].id).toBe('freeze_collision');expect(t.currentState.scalars.defensible_benefit_usd).toBeGreaterThan(8000000);expect(t.currentState.outcome).toBe('win_with_scars');});
 it('inherits the persisted R3 metric set at R10',()=>{const g=run(),t=g.teams[0],r10=t.results.find(x=>x.round===10)!;expect(t.artifacts.find(x=>x.type==='round3_analysis')?.studentContent.metricSet).toEqual([metric]);expect(r10.derived.monitoringMetrics).toEqual([metric]);});
 it('B automation without governance selects the actual highest risks and lands in the $5M–$8M band',()=>{const weak={...base[5],automation_depth:'D',automates_authorization:true,sourcing:'full_bpo',parameter_set:{threshold_usd:null,threshold_owner:null,change_detection:null,queue_owner_and_authority:null,rollback_trigger:null,patient_escalation_path:null}};const g=run({2:{discovery_allocation:{document_analysis:100,structured_interviews:0,process_mining:0,floor_observation:0},discovery_scope:'denials_only'},6:weak,8:{go_decision:true,cutover_controls:[]},10:{sustainment:['named_process_owner','monitoring_metrics'],metric_strategy:'inherit',board_narrative:{claimed_benefit_usd:3000000,disclosure_items:['crisis_occurred']},vendor_governance:[]}},'weak'),t=g.teams[0],ranked=Object.values(t.currentState.risks).filter(x=>x.eligible).sort((a,b)=>b.exposure-a.exposure);expect(t.currentState.crises[0].id).toBe(ranked[0].id);expect(t.currentState.crises.length).toBeGreaterThan(0);expect(t.currentState.scalars.realized_benefit_usd).toBeLessThan(13000000);expect(t.currentState.outcome).toBe('win_with_scars');});
 it('C credibility failure with restatement is Disaster',()=>{const g=run({1:{opening_posture:'continue_clearpath',savings_commitment_made:true,savings_commitment_usd:12000000,memo_handling:'found_suppressed'},3:{...base[2],published_baseline:'adopt_inherited'}}),t=g.teams[0];expect(t.currentState.risks.restatement.exposure).toBeGreaterThanOrEqual(65);expect(t.currentState.scalars.defensible_benefit_usd!).toBeLessThan(t.currentState.scalars.realized_benefit_usd!);expect(t.currentState.crises.some(x=>x.id==='restatement')).toBe(true);expect(t.currentState.outcome).toBe('disaster');});
 it('D preserves analytical strength while political relationships deteriorate',()=>{const g=run({4:{root_cause_claim:{primary_component:'eligibility_front_end_data',secondary_component:'authorization_workflow',weights:[34,27],framing:'named_individual'}},5:{redesign_ambition:'clean_sheet',design_room:['frontline_staff','physicians'],process_ownership:'ntende'},7:{implementation_approach:'system_wide',coalition_actions:[],budget_allocation:{training:300000,contingency_reserve:2500000}},8:{go_decision:true,cutover_controls:['manual_fallback']}}),t=g.teams[0],r4=t.results.find(x=>x.round===4)!;expect((r4.hiddenScores.root_cause_claim as {total:number}).total).toBeGreaterThan(.9);expect(t.currentState.stakeholders.ntende.trust).toBeLessThan(cloneConfig().stakeholders.ntende.trust);expect(t.currentState.risks.grievance.exposure+t.currentState.risks.freeze_collision.exposure).toBeGreaterThanOrEqual(60);});
 it('uses one cumulative ledger with exact final balance',()=>{const g=run({10:{sustainment:['named_process_owner','monitoring_metrics','exception_review_cadence','change_governance'],metric_strategy:'rebuild',board_narrative:{claimed_benefit_usd:8000000,disclosure_items:['assumptions_stated']}}}),budget=g.teams[0].currentState.budget;expect(budget.remaining).toBe(budget.initial-budget.ledger.reduce((n,x)=>n+x.amount,0));expect(budget.ledger.find(x=>x.item==='metric_set_rebuild')?.amount).toBe(85000);});
});
