import {randomUUID} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import type {Server} from 'node:http';
import {createElement} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {afterAll,beforeAll,describe,expect,it} from 'vitest';
import {InstructorSessionRegistry} from '../src/application/instructor-auth.js';
import {teamAccessCode} from '../src/application/access.js';
import {SimulationService} from '../src/application/service.js';
import {instructorProjection,studentProjection,studentDebrief} from '../src/application/projections.js';
import {cloneConfig} from '../src/domain/config.js';
import {closeRound,createGame,replayGame,submit} from '../src/domain/engine.js';
import {correctSubmission,passivePayload,releaseWithOutstanding} from '../src/domain/instructor.js';
import type {Game,RoundNumber} from '../src/domain/types.js';
import {MemoryGameRepository} from '../src/persistence/repository.js';
import {SqliteGameRepository} from '../src/persistence/sqlite.js';
import {createApp} from '../src/server/index.js';
import {InstructorActions,SubmissionCorrection} from '../src/web/components/InstructorActions.js';
import type {InstructorView} from '../src/web/api.js';
import {roundPayloads} from '../src/web/rounds.js';

const r1={opening_posture:'continue_clearpath',savings_commitment_made:false,savings_commitment_usd:null,memo_handling:'not_found'};
const normalized=(g:Game)=>({...g,teams:g.teams.map(t=>({...t,artifacts:[...t.artifacts].sort((a,b)=>a.id.localeCompare(b.id))}))});
const fresh=()=>createGame({teamNames:['Alpha','Beta'],config:cloneConfig()});
const action=(game:Game)=>({actor:'instructor' as const,round:game.activeRound,confirmed:true as const,outstandingTeamIds:game.teams.filter(t=>!t.submissions.some(s=>s.round===game.activeRound)).map(t=>t.id)});
function toRound(round:number){let g=fresh();for(let n=1;n<round;n++){for(const t of g.teams){let p=structuredClone(roundPayloads[n]);if(n===1)p=r1;if(n===3)p={constraint_claim:{station:'authorization',shortfall_estimate:91,implication_text:'Verification is upstream of authorization.'},published_baseline:'defer',artifact:{bottleneckMap:{stations:[{station:'authorization'}]},metricSet:[{id:'test',label:'Test metric',category:'test',unit:'cases'}]}};if(n===6)p=passivePayload(6,t);if(n===7)p=passivePayload(7,t);if(n===9)p=t.currentState.crises.length?passivePayload(9,t):{presented_figure:{figure_type:'decline_to_quantify',figure_usd:null,basis_text:'Test fixture declines a claim.'},disclosure_items:[]};g=submit(g,t.id,p);}g=closeRound(g);}return g;}

describe('Phase 7 corrections',()=>{
 it('replaces only open payload and records each changed lever with identity and timestamp',()=>{const g=submit(fresh(),'team-1',r1,'original team'),old=g.teams[0].submissions[0],timestamp='2026-09-16T10:00:00Z',next=correctSubmission(g,'team-1',{...r1,opening_posture:'pause_pilot',savings_commitment_made:true,savings_commitment_usd:123},{actor:'instructor',round:1},timestamp),s=next.teams[0].submissions[0];expect(s).toMatchObject({id:old.id,submitter:old.submitter,submittedAt:old.submittedAt});expect(s.corrections?.[0]).toMatchObject({gameId:g.id,teamId:'team-1',round:1,actor:'instructor',action:'instructor_correction',timestamp});expect(s.corrections?.[0].changes).toHaveLength(3);expect(s.corrections?.[0].changes[0]).toEqual({field:'opening_posture',oldValue:'continue_clearpath',newValue:'pause_pilot'});expect(g.teams[0].submissions[0]).toEqual(old);expect(next.teams[1]).toEqual(g.teams[1]);expect(next.teams[0].results).toEqual(g.teams[0].results);});
 it('shows corrected values but never audit metadata in student history/debrief',()=>{const g=correctSubmission(submit(fresh(),'team-1',r1),'team-1',{...r1,opening_posture:'pause_pilot'},{actor:'instructor',round:1});const student=studentProjection(g,'team-1');expect(student.history[0].payload.opening_posture).toBe('pause_pilot');for(const forbidden of ['corrections','oldValue','newValue','instructor_correction'])expect(JSON.stringify([student,studentDebrief(g.teams[0])])).not.toContain(forbidden);expect(instructorProjection(g).teams[0].submissions[0].corrections).toHaveLength(1);});
 it('rejects no-op corrections',()=>{const g=submit(fresh(),'team-1',r1);expect(()=>correctSubmission(g,'team-1',r1,action(g))).toThrow('must change');});
 it('rejects invalid corrected levers through the existing schema',()=>{const g=submit(fresh(),'team-1',r1);expect(()=>correctSubmission(g,'team-1',{...r1,opening_posture:'invented'},action(g))).toThrow();});
 it('does not grant teams resubmission after correction',()=>{let g=submit(fresh(),'team-1',r1);g=correctSubmission(g,'team-1',{...r1,opening_posture:'pause_pilot'},action(g));expect(()=>submit(g,'team-1',r1)).toThrow('immutable');});
 it('rejects closed rounds and leaves historical results untouched',()=>{const g=toRound(2),before=structuredClone(g);expect(()=>correctSubmission(g,'team-1',r1,{actor:'instructor',round:1})).toThrow('open round');expect(g).toEqual(before);});
 it('rejects completed games',()=>{const g={...submit(fresh(),'team-1',r1),status:'completed' as const};expect(()=>correctSubmission(g,'team-1',r1,action(g))).toThrow('open round');});
 it('rejects missing team or missing accepted submission',()=>{const g=fresh();expect(()=>correctSubmission(g,'absent',r1,action(g))).toThrow('Team not found');expect(()=>correctSubmission(g,'team-1',r1,action(g))).toThrow('No accepted');});
 it('preserves memo access validation at the service boundary',()=>{const repo=new MemoryGameRepository(),service=new SimulationService(repo),g=service.create(['A']);service.submit(g.id,g.teams[0].id,r1,'team');expect(()=>service.correct(g.id,g.teams[0].id,{...r1,memo_handling:'raised_deiss'},action(g))).toThrow('Open the analyst memo');});
 it('appends sequential corrections without recalculating state',()=>{let g=submit(fresh(),'team-1',r1);g=correctSubmission(g,'team-1',{...r1,opening_posture:'pause_pilot'},action(g));g=correctSubmission(g,'team-1',{...r1,opening_posture:'restart_discovery'},action(g));expect(g.teams[0].submissions[0].corrections?.[1].changes[0].oldValue).toBe('pause_pilot');expect(g.teams[0].currentState.round).toBe(0);});
});

describe('Phase 7 non-submission resolution',()=>{
 it('ordinary closure still blocks missing teams',()=>expect(()=>closeRound(submit(fresh(),'team-1',r1))).toThrow('Every team must submit'));
 it('requires explicit confirmation and a fresh outstanding-team list',()=>{const g=fresh();expect(()=>releaseWithOutstanding(g,{...action(g),confirmed:false as never})).toThrow('confirmation');expect(()=>releaseWithOutstanding(g,{...action(g),outstandingTeamIds:['team-1']})).toThrow('changed');});
 it('preserves submitted decisions and distinguishes identical passive decisions',()=>{const g=submit(fresh(),'team-1',r1),next=releaseWithOutstanding(g,action(g));expect(next.activeRound).toBe(2);expect(next.teams[0].submissions).toEqual(g.teams[0].submissions);expect(next.teams[1].submissions).toHaveLength(1);expect(next.teams[1].submissions[0].kind).toBe('non_submission');expect(next.teams[0].submissions[0].kind).toBeUndefined();expect(studentProjection(next,'team-2').history[0].status).toBe('NON-SUBMISSION');expect(studentDebrief(next.teams[1]).panels[0].entries?.[0]).toMatchObject({status:'NON-SUBMISSION'});});
 it('ordinary all-submitted release is unchanged and cannot duplicate an override',()=>{let g=fresh();for(const t of g.teams)g=submit(g,t.id,r1);expect(closeRound(g).activeRound).toBe(2);expect(()=>releaseWithOutstanding(g,action(g))).toThrow('normal release');const missing=fresh(),a=action(missing),next=releaseWithOutstanding(missing,a);expect(()=>releaseWithOutstanding(next,a)).toThrow('open round');});
 it('does not accept a student-forged non-submission marker',()=>{const g=submit(fresh(),'team-1',{...r1,kind:'non_submission',corrections:[{actor:'instructor'}]});expect(g.teams[0].submissions[0].kind).toBeUndefined();expect(g.teams[0].submissions[0].payload).toEqual(r1);});
 it('rejects completion and a non-instructor domain command',()=>{const g=fresh();expect(()=>releaseWithOutstanding({...g,status:'completed'},action(g))).toThrow('open round');expect(()=>releaseWithOutstanding(g,{...action(g),actor:'student' as never})).toThrow('Instructor action');});
 for(const round of [1,5,6,7,8,10] as RoundNumber[])it(`resolves R${round} passive values through normal computation and replay`,()=>{const g=toRound(round),a=action(g),next=releaseWithOutstanding(g,a);let expected=g;for(const t of g.teams)expected=submit(expected,t.id,passivePayload(round,t));expected=closeRound(expected);expect(next.teams.map(t=>t.currentState)).toEqual(expected.teams.map(t=>t.currentState));expect(next.teams.map(t=>t.results)).toEqual(expected.teams.map(t=>t.results));expect(next.teams[0].submissions.slice(0,-1)).toEqual(g.teams[0].submissions);expect(replayGame(next).teams[0].currentState).toEqual(next.teams[0].currentState);});
 for(const round of [2,3,4] as RoundNumber[])it(`resolves authoritative R${round} absence without relaxing participant validation`,()=>{const repo=new MemoryGameRepository(),g=toRound(round);repo.create(g);const service=new SimulationService(repo);expect(()=>submit(g,'team-1',passivePayload(round,g.teams[0]))).toThrow();const next=service.override(g.id,action(g));expect(next.activeRound).toBe(round+1);expect(next.teams[0].submissions.at(-1)?.kind).toBe('non_submission');expect(next.teams[0].submissions.slice(0,-1)).toEqual(g.teams[0].submissions);});
 it('represents absent R9 figure without basis text and preserves crisis responses',()=>{const g=toRound(9),team=g.teams[0];expect(passivePayload(9,{...team,currentState:{...team.currentState,crises:[]}})).toEqual({});expect(team.currentState.crises.length).toBeGreaterThan(0);const next=releaseWithOutstanding(g,action(g));expect(next.activeRound).toBe(10);expect(next.teams[0].submissions.at(-1)?.payload).toEqual(passivePayload(9,team));expect(next.teams[0].results.at(-1)?.derived.scenario).toBe('crisis');});
 it('renders outstanding team names and keeps confirmation separate from normal release',()=>{const view=instructorProjection(fresh()) as unknown as InstructorView,html=renderToStaticMarkup(createElement(InstructorActions,{view,onOverride:async()=>{}}));expect(html).toContain('Alpha');expect(html).toContain('Beta');expect(html).toContain('Release with outstanding teams');expect(html).not.toContain('Confirm release with outstanding teams');});
 it('renders an instructor-only correction editor with the actual accepted values',()=>{const g=submit(fresh(),'team-1',r1),html=renderToStaticMarkup(createElement(SubmissionCorrection,{submission:g.teams[0].submissions[0],teamName:'Alpha',onSave:async()=>{}}));expect(html).toContain('continue_clearpath');expect(html).toContain('Save instructor correction');});
});

describe('Phase 7 SQLite durability',()=>{
 it('retains corrections, old/new audit and non-submissions across close/reopen and replay',()=>{const dir=mkdtempSync(join(tmpdir(),'flexee-phase7-')),path=join(dir,'test.sqlite');let repo=new SqliteGameRepository(path);try{let service=new SimulationService(repo);const g=service.create(['A','B']),id=g.id;service.submit(id,g.teams[0].id,r1,'team');const corrected=service.correct(id,g.teams[0].id,{...r1,opening_posture:'pause_pilot'},action(g));repo.close();repo=new SqliteGameRepository(path);service=new SimulationService(repo);expect(normalized(service.get(id))).toEqual(normalized(corrected));const closed=service.override(id,action(corrected));repo.close();repo=new SqliteGameRepository(path);expect(normalized(repo.get(id)!)).toEqual(normalized(closed));repo.save(replayGame(repo.get(id)!));expect(repo.get(id)?.teams[0].submissions[0].corrections).toEqual(corrected.teams[0].submissions[0].corrections);expect(repo.get(id)?.teams[1].submissions[0].kind).toBe('non_submission');}finally{repo.close();rmSync(dir,{recursive:true,force:true});}});
});

describe('Phase 7 HTTP authorization',()=>{
 const repo=new MemoryGameRepository(),service=new SimulationService(repo),secret=randomUUID();let server:Server,base:string,credential:string,studentToken:string,g:Game;
 const request=async(path:string,method='GET',token?:string,body?:unknown)=>{const response=await fetch(base+path,{method,headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})});return {status:response.status,body:await response.json()};};
 beforeAll(async()=>{g=service.create(['A','B']);server=createApp(repo,secret).listen(0,'127.0.0.1');await new Promise<void>(resolve=>server.once('listening',resolve));base=`http://127.0.0.1:${(server.address() as {port:number}).port}`;credential=(await request('/api/instructor/session','POST',undefined,{passphrase:secret})).body.token;studentToken=(await request('/api/student/session','POST',undefined,{gameId:g.id,teamCode:teamAccessCode(g.id,g.teams[0].id)})).body.token;});
 afterAll(async()=>{server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));});
 it('accepts correct passphrase and rejects wrong/missing configured passphrase safely',async()=>{expect(credential).toBeTruthy();expect(await request('/api/instructor/session','POST',undefined,{passphrase:'wrong'})).toEqual({status:404,body:{error:'Not found'}});expect(new InstructorSessionRegistry(undefined).authenticate('anything')).toBeUndefined();expect(new InstructorSessionRegistry('').authenticate('')).toBeUndefined();});
 const paths=[['GET','/api/games'],['POST','/api/games'],['GET','/api/games/GAME/instructor'],['POST','/api/games/GAME/close'],['POST','/api/games/GAME/close-with-outstanding'],['POST','/api/games/GAME/teams/TEAM/submissions/1/correction'],['GET','/API/GAMES/GAME/INSTRUCTOR/']];
 for(const [method,path] of paths)for(const credentialKind of ['absent','invalid','student'])it(`${method} ${path} hides instructor resources from ${credentialKind} credentials`,async()=>{const expected=await request('/api/no-such-resource',method);const actual=await request(path.replace('GAME',g.id).replace('TEAM',g.teams[0].id),method,credentialKind==='student'?studentToken:credentialKind==='invalid'?'invalid':undefined,method==='POST'?{}:undefined);expect(actual).toEqual(expected);});
 it('allows instructor diagnostics and keeps the credential out of responses',async()=>{const result=await request(`/api/games/${g.id}/instructor`,'GET',credential);expect(result.status).toBe(200);expect(result.body.teams[0].state.risks).toBeDefined();expect(JSON.stringify(result.body)).not.toContain(secret);expect(JSON.stringify(result.body)).not.toContain(credential);});
 it('missing authenticated game looks like a nonexistent resource',async()=>expect(await request('/api/games/absent/instructor','GET',credential)).toEqual(await request('/api/no-such-resource')));
 it('preserves student access and rejects instructor tokens as student credentials',async()=>{expect((await request(`/api/games/${g.id}/teams/${g.teams[0].id}`,'GET',studentToken)).status).toBe(200);expect((await request(`/api/games/${g.id}/teams/${g.teams[1].id}`,'GET',studentToken)).status).toBe(400);expect((await request(`/api/games/${g.id}/teams/${g.teams[0].id}`,'GET',credential)).status).toBe(400);});
 it('allows authenticated correction and override, and hides correction audit from students',async()=>{expect((await request(`/api/games/${g.id}/teams/${g.teams[0].id}/submissions`,'POST',studentToken,{payload:r1})).status).toBe(201);const result=await request(`/api/games/${g.id}/teams/${g.teams[0].id}/submissions/1/correction`,'POST',credential,{payload:{...r1,opening_posture:'pause_pilot'}});expect(result.status).toBe(200);expect(result.body.teams[0].submissions[0].corrections).toHaveLength(1);const student=await request(`/api/games/${g.id}/teams/${g.teams[0].id}`,'GET',studentToken);expect(student.body.history[0].payload.opening_posture).toBe('pause_pilot');expect(JSON.stringify(student.body)).not.toContain('instructor_correction');expect((await request(`/api/games/${g.id}/close`,'POST',credential)).status).toBe(400);const released=await request(`/api/games/${g.id}/close-with-outstanding`,'POST',credential,{round:1,confirmed:true,outstandingTeamIds:[g.teams[1].id]});expect(released.status).toBe(200);expect(released.body.game.activeRound).toBe(2);expect(released.body.teams[1].submissions[0].kind).toBe('non_submission');});
 it('allows authenticated ordinary release with all teams submitted',async()=>{const all=service.create(['C']);service.submit(all.id,all.teams[0].id,r1,'team');expect((await request(`/api/games/${all.id}/close`,'POST',credential)).body.game.activeRound).toBe(2);});
});
