import {describe,expect,it} from 'vitest';
import {readFileSync} from 'node:fs';
import {artifactCatalog,markArtifactAccess,suppliedClearpathFilenames} from '../src/domain/artifacts.js';
import {cloneConfig} from '../src/domain/config.js';
import {createGame} from '../src/domain/engine.js';
import {DeterministicConversationProvider,inferDirectFactualQuestion} from '../src/domain/conversations.js';
import {neverSaw,studentDebrief,studentProjection} from '../src/application/projections.js';
import {SimulationService} from '../src/application/service.js';
import {MemoryGameRepository} from '../src/persistence/repository.js';
import {roundPayloads} from '../src/web/rounds.js';
import type {RoundNumber,StakeholderId,Team} from '../src/domain/types.js';

const team=()=>createGame({teamNames:['T'],config:cloneConfig()}).teams[0];
const transcript=(t:Team,actorId:StakeholderId,userMessage:string,actorReply:string)=>{t.transcripts.push({id:crypto.randomUUID(),gameId:'g',teamId:t.id,round:2,actorType:'stakeholder',actorId,userMessage,actorReply,timestamp:'2026-09-08T00:00:00.000Z',contextHash:'test'});};
const submitAt=(t:Team,round:RoundNumber,payload:Record<string,unknown>)=>{t.submissions.push({id:`s${round}`,gameId:'g',teamId:t.id,round,payload,submitter:'test',submittedAt:'2026-09-08T00:00:00.000Z',configVersion:'bpm-v1',configHash:'test'});};
const label={memo:'The Reyes memo contained information you never saw.',reyes:'Reyes had information she never shared with you.',marisol:'Marisol had information she never shared with you.',tyrell:'Tyrell had information he never shared with you.',sylvia:'Sylvia had information she never shared with you.',kubiak:'Kubiak had information he never shared with you.',walters:'Walters had an offer she never shared with you.',v3:'Version 3 of the board deck contained information you never saw.',page9:'Page nine of the readiness assessment contained information you never saw.',anand:'Anand had information she never shared with you.'} as const;
const validPayload=(round:number)=>{const payload=structuredClone(roundPayloads[round]);if(round===3){(payload.constraint_claim as Record<string,unknown>).implication_text='A testable implication.';const metric=(((payload.artifact as Record<string,unknown>).metricSet as Array<Record<string,unknown>>)[0]);Object.assign(metric,{label:'First-pass rate',category:'quality',unit:'percent'});}if(round===6)(payload.parameter_set as Record<string,unknown>).rollback_trigger=null;return payload;};
describe('Phase 4 CLEARPATH and artifact interface',()=>{
 it('contains exactly 63 folder items',()=>expect((artifactCatalog.find(a=>a.id==='clearpath_all')!.studentContent.entries as unknown[])).toHaveLength(63));
 it('preserves all 45 supplied filenames byte-for-byte and in order',()=>{const entries=(artifactCatalog.find(a=>a.id==='clearpath_all')!.studentContent.entries as Array<{title:string}>).map(e=>e.title);expect(entries.slice(-45)).toEqual([...suppliedClearpathFilenames]);});
 it('preserves deliberate inconsistent names and the empty placeholder',()=>{expect(suppliedClearpathFilenames).toContain('processmap_patientaccess_v2 FINAL.vsdx');expect(suppliedClearpathFilenames).toContain('scoring_matrix_v2_FINAL.xlsx');expect(JSON.stringify(artifactCatalog)).toContain('lessons_learned_placeholder.docx');});
 it('tracks page nine and board v3 through the existing evidence state',()=>{let t=team();t.artifacts=structuredClone(artifactCatalog);t.currentState.evidence.readiness_assessment={id:'readiness_assessment',available:true,discovered:true,accessed:false};t.currentState.evidence.doug_board_deck={id:'doug_board_deck',available:true,discovered:true,accessed:false};t=markArtifactAccess(t,'readiness_assessment',{page:9});t=markArtifactAccess(t,'doug_board_deck',{versionId:'v3'});expect(t.currentState.evidence.readiness_assessment.accessedPages).toEqual([9]);expect(t.currentState.evidence.doug_board_deck.accessedVersions).toEqual(['v3']);});
 it('keeps pages 10–14 explicit placeholders',()=>{const pages=artifactCatalog.find(a=>a.id==='readiness_assessment')!.pages!;expect(pages.slice(9)).toHaveLength(5);expect(pages.slice(9).every(p=>p.content.includes('authoritative body not supplied'))).toBe(true);expect(pages[8].content).toContain('$200,000');});
});
describe('Phase 4 deterministic conversation',()=>{
 it('recognizes an arbitrary direct lane question',()=>expect(inferDirectFactualQuestion('What refresh does the Monday eligibility interface use?','kubiak')).toBe(true));
 it('answers a known fact truthfully at low trust without volunteering',async()=>{const t=team(),reply=await new DeterministicConversationProvider().reply({gameId:'g',teamId:'t',round:1,actorType:'stakeholder',actorId:'kubiak',message:'What refresh does the Monday eligibility interface use?',state:t.currentState,directFactualQuestion:true});expect(reply).toContain('Sunday nights');expect(reply).not.toContain('ticket, not a project');});
 it('returns an in-character knowledge limitation outside the lane',async()=>{const t=team(),reply=await new DeterministicConversationProvider().reply({gameId:'g',teamId:'t',round:1,actorType:'stakeholder',actorId:'kubiak',message:'What is the union waiver?',state:t.currentState,directFactualQuestion:true});expect(reply).toContain('outside');});
});
describe('Phase 4 debrief',()=>{
 it('has exactly three panels, nine state series, ten rounds, and eighteen stakeholder series',()=>{const t=team();t.stateHistory=Array.from({length:10},(_,i)=>({...structuredClone(t.currentState),round:(i+1) as RoundNumber}));const d=studentDebrief(t),m=d.panels[1] as {rounds:number[];stateSeries:unknown[];stakeholderSeries:unknown[]};expect(d.panels.map(p=>p.title)).toEqual(['Decision Log','What Moved','What You Never Saw']);expect(m.rounds).toHaveLength(10);expect(m.stateSeries).toHaveLength(9);expect(m.stakeholderSeries).toHaveLength(18);});
 it('preserves student-authored decision values, date, and member',()=>{const t=team();t.submissions=[{id:'s',gameId:'g',teamId:'team-1',round:3,payload:{constraint_claim:{station:'scheduling',shortfall_estimate:17,implication_text:'our exact words'}},submitter:'Student A',submittedAt:'2026-09-03T00:00:00Z',configVersion:'bpm-v1',configHash:'x'}];expect(JSON.stringify(studentDebrief(t))).toContain('our exact words');expect(JSON.stringify(studentDebrief(t))).toContain('Student A');});
 it('derives one-line inventory sentences from per-run access',()=>{const a=team(),b=team();a.currentState.evidence.analyst_memo.accessed=true;b.currentState.evidence.analyst_memo.accessed=false;expect(neverSaw(a)).not.toContain(label.memo);expect(neverSaw(b)).toContain(label.memo);expect(neverSaw(b).every(x=>x.endsWith('.')&&!x.includes(':'))).toBe(true);});
 it('does not expose conversation gates or advisor internals to students',()=>{const json=JSON.stringify(studentProjection(createGame({teamNames:['T'],config:cloneConfig()}),'team-1'));for(const secret of ['directFactualQuestion','disclosureAvailability','rationale_tags','focus_lever','conditionResults'])expect(json).not.toContain(secret);});
 it('renders threshold with no placeholder and monitoring without inheritance wording',()=>{const source=readFileSync('src/web/components/DecisionWorkspaceV6.tsx','utf8'),projection=readFileSync('src/application/projections.ts','utf8');expect(source).not.toContain('placeholder=');expect(source).toContain('Monitoring metrics');expect(source).not.toContain('Inherited metrics');expect(projection).toContain('No rollback trigger on file.');});
});
describe('Phase 4 Panel 3 exact access predicates',()=>{
 it('does not open Tyrell database for generic structured interviews',()=>{const t=team();submitAt(t,2,{discovery_allocation:{structured_interviews:100}});expect(neverSaw(t)).toContain(label.tyrell);});
 it('opens Tyrell database for an explicit denials-bench evidence access',()=>{const t=team();t.currentState.evidence.boyce_database.accessed=true;expect(neverSaw(t)).not.toContain(label.tyrell);});
 it('opens Tyrell database after the qualifying root-cause answer',()=>{const t=team();transcript(t,'boyce','How do you categorize root causes?','The official report sorts by denial code. I built a separate twelve-month view categorized by what caused the denial.');expect(neverSaw(t)).not.toContain(label.tyrell);});
 it('does not open Tyrell database through an unrelated stakeholder interaction',()=>{const t=team();transcript(t,'anand','How many denials are there?','That is not my data.');expect(neverSaw(t)).toContain(label.tyrell);});
 it('does not open Marisol card for floor-allocation alone',()=>{const t=team();submitAt(t,2,{discovery_allocation:{floor_observation:100}});expect(neverSaw(t)).toContain(label.marisol);});
 it('opens Marisol card for the persisted west-campus desk observation',()=>{const t=team();t.roundNarratives.push({round:3,variantId:'r3-observation-thread',conditionResults:[],renderedContent:'student narrative'});expect(neverSaw(t)).not.toContain(label.marisol);});
 it.each(['survey','interview request','meeting'])('does not open Marisol card for a %s',activity=>{const t=team();transcript(t,'ferrara',activity,'It is fine. You just have to know a couple of things.');expect(neverSaw(t)).toContain(label.marisol);});
 it('does not open Kubiak feed for technical partnership alone',()=>{const t=team();t.currentState.scalars.technical_partnership=70;expect(neverSaw(t)).toContain(label.kubiak);});
 it('opens Kubiak feed after the qualifying IT process answer',()=>{const t=team();transcript(t,'kubiak','When does the eligibility feed refresh?','The eligibility feed refreshes Sunday nights. Monday registrations verify against Friday data.');expect(neverSaw(t)).not.toContain(label.kubiak);});
 it('opens Kubiak feed after the non-accusatory R4 spontaneous readout',()=>{const t=team();submitAt(t,4,{root_cause_claim:{framing:'system_condition'}});expect(neverSaw(t)).not.toContain(label.kubiak);});
 it.each(['function','named_individual'])('does not treat %s R4 framing as the spontaneous readout',framing=>{const t=team();submitAt(t,4,{root_cause_claim:{framing}});expect(neverSaw(t)).toContain(label.kubiak);});
 it('requires exact access or authoritative disclosure for every inventory item',()=>{const t=team();t.currentState.stakeholders.ntende.trust=100;t.currentState.scalars.technical_partnership=100;submitAt(t,5,{design_room:['union']});submitAt(t,7,{coalition_actions:['anand_concrete_commitment']});expect(neverSaw(t)).toEqual([label.memo,label.reyes,label.marisol,label.tyrell,label.sylvia,label.kubiak,label.v3,label.page9,label.anand]);});
 it('keeps the prescribed sentences free of mechanics after exact events open selected items',()=>{const t=team();t.currentState.evidence.boyce_database.accessed=true;const panel=studentDebrief(t).panels[2] as {items:string[]};expect(panel.items).not.toContain(label.tyrell);expect(panel.items).toContain('Sylvia had information she never shared with you.');expect(panel.items.every(item=>item.endsWith('.')&&!item.includes(':'))).toBe(true);expect(JSON.stringify(panel)).not.toMatch(/boyce_database|structured_interviews|condition|predicate/i);});
 it('produces different inventories for materially different paths',()=>{const a=team(),b=team();submitAt(a,4,{root_cause_claim:{framing:'system_condition'}});submitAt(b,4,{root_cause_claim:{framing:'named_individual'}});expect(neverSaw(a)).not.toEqual(neverSaw(b));expect(neverSaw(b)).toContain(label.kubiak);});
 it('keeps genuinely missed sources in a disciplined Path A-shaped run',()=>{const t=team();submitAt(t,2,{discovery_allocation:{document_analysis:5,structured_interviews:25,process_mining:30,floor_observation:40}});submitAt(t,4,{root_cause_claim:{framing:'system_condition'}});submitAt(t,5,{design_room:['union']});t.roundNarratives.push({round:3,variantId:'r3-observation-thread+r3-mining-thread',conditionResults:[],renderedContent:'student narrative'});expect(neverSaw(t)).toEqual([label.memo,label.reyes,label.tyrell,label.sylvia,label.v3,label.page9,label.anand]);});
});
describe('Phase 4 load-bearing access enforcement',()=>{
 it('requires actual memo access for every non-not-found R1 handling choice',()=>{const repo=new MemoryGameRepository(),service=new SimulationService(repo),g=service.create(['T']);const raised={...roundPayloads[1],memo_handling:'raised_deiss'};expect(()=>service.submit(g.id,'team-1',raised,'test')).toThrow('Open the analyst memo');service.evidence(g.id,'team-1','analyst_memo');expect(()=>service.submit(g.id,'team-1',raised,'test')).not.toThrow();expect(service.get(g.id).teams[0].currentState.evidence.analyst_memo.accessed).toBe(true);});
 it('permits system-effective not-found only while the memo is unopened',()=>{const repo=new MemoryGameRepository(),service=new SimulationService(repo),g=service.create(['T']);expect(()=>service.submit(g.id,'team-1',structuredClone(roundPayloads[1]),'test')).not.toThrow();});
 it('keeps board v3 optional evidence for the R3 baseline decision',()=>{const repo=new MemoryGameRepository(),service=new SimulationService(repo),g=service.create(['T']);for(const round of [1,2]){service.submit(g.id,'team-1',validPayload(round),'test');service.close(g.id);}const before=service.get(g.id).teams[0].currentState.evidence.doug_board_deck;expect(before.accessedVersions).toBeUndefined();expect(()=>service.submit(g.id,'team-1',validPayload(3),'test')).not.toThrow();});
 it('keeps page nine optional evidence for a $200,000 readiness allocation and R8 decision',()=>{const repo=new MemoryGameRepository(),service=new SimulationService(repo),g=service.create(['T']);for(let round=1;round<=6;round++){service.submit(g.id,'team-1',validPayload(round),'test');service.close(g.id);}const r7=validPayload(7);r7.budget_allocation={training:200000,contingency_reserve:2600000};service.submit(g.id,'team-1',r7,'test');service.close(g.id);expect(service.get(g.id).teams[0].currentState.evidence.readiness_assessment.accessedPages).toBeUndefined();expect(()=>service.submit(g.id,'team-1',validPayload(8),'test')).not.toThrow();});
 it('makes the paginated readiness assessment openable when Round 7 begins',()=>{const repo=new MemoryGameRepository(),service=new SimulationService(repo),g=service.create(['T']);for(let round=1;round<=6;round++){service.submit(g.id,'team-1',validPayload(round),'test');service.close(g.id);}expect(service.get(g.id).teams[0].currentState.evidence.readiness_assessment.available).toBe(true);expect(()=>service.evidence(g.id,'team-1','readiness_assessment',{page:9})).not.toThrow();expect(service.get(g.id).teams[0].currentState.evidence.readiness_assessment.accessedPages).toEqual([9]);});
});
