import {mkdtempSync,readFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {describe,expect,it} from 'vitest';
import {StudentSessionRegistry,teamAccessCode} from '../src/application/access.js';import {instructorProjection,studentProjection} from '../src/application/projections.js';import {SimulationService} from '../src/application/service.js';import {cloneConfig} from '../src/domain/config.js';import {createGame} from '../src/domain/engine.js';import {MemoryGameRepository} from '../src/persistence/repository.js';import {SqliteGameRepository} from '../src/persistence/sqlite.js';
const r1={opening_posture:'pause_pilot',savings_commitment_made:false,savings_commitment_usd:null,memo_handling:'not_found'};
describe('Phase 5 advisor consultation',()=>{
 it('projects all six advisors in fixed non-valence order',()=>expect(studentProjection(createGame({teamNames:['T'],config:cloneConfig()}),'team-1').advisors).toEqual(['marchetti','oyelaran','castellanos','brennan','kowalczyk','okonkwo']));
 it('accepts free-form questions and persists advisor consultations across rounds',async()=>{const repo=new MemoryGameRepository(),service=new SimulationService(repo),g=service.create(['T']);await service.converse(g.id,'team-1',{actorType:'advisor',actorId:'marchetti',message:'Which assumption is weakest?'});service.submit(g.id,'team-1',r1,'member');service.close(g.id);await service.converse(g.id,'team-1',{actorType:'advisor',actorId:'marchetti',message:'What changed since our first discussion?'});const history=studentProjection(service.get(g.id),'team-1').transcripts.filter(t=>t.actorType==='advisor');expect(history.map(t=>[t.round,t.userMessage])).toEqual([[1,'Which assumption is weakest?'],[2,'What changed since our first discussion?']]);});
 it('uses question context without mutating the scoring-derived stance',async()=>{const repo=new MemoryGameRepository(),service=new SimulationService(repo),g=service.create(['T']);service.submit(g.id,'team-1',r1,'member');service.close(g.id);const before=structuredClone(service.get(g.id).teams[0].results[0].advisorStances);await service.converse(g.id,'team-1',{actorType:'advisor',actorId:'brennan',message:'What should we ask the sponsor?'});expect(service.get(g.id).teams[0].results[0].advisorStances).toEqual(before);});
 it('survives SQLite persistence with the original advisor exchange',async()=>{const dir=mkdtempSync(join(tmpdir(),'flexee-phase5-')),repo=new SqliteGameRepository(join(dir,'test.sqlite'));try{const service=new SimulationService(repo),g=service.create(['T']),saved=await service.converse(g.id,'team-1',{actorType:'advisor',actorId:'okonkwo',message:'What can we make visible?'}),loaded=service.get(g.id).teams[0].transcripts[0];expect(loaded).toMatchObject({actorType:'advisor',userMessage:'What can we make visible?',actorReply:saved.actorReply});}finally{repo.close();rmSync(dir,{recursive:true,force:true});}});
 it('does not render advisor consensus or aggregation',()=>expect(readFileSync('src/web/components/StudentDashboardV6.tsx','utf8')).not.toMatch(/of 6 support|consensus percentage|support count|opposition count|majority indicator/i));
});
describe('Phase 5 team access',()=>{
 it('joins a specific team by code and keeps session identity stable',()=>{const game=createGame({teamNames:['Zulu','Alpha'],config:cloneConfig()}),sessions=new StudentSessionRegistry(),joined=sessions.join(game,teamAccessCode(game.id,'team-2'));expect(joined.teamId).toBe('team-2');expect(sessions.require(joined.token,game.id,'team-2')).toEqual({gameId:game.id,teamId:'team-2'});});
 it('rejects invalid codes and cross-team use',()=>{const game=createGame({teamNames:['A','B'],config:cloneConfig()}),sessions=new StudentSessionRegistry(),joined=sessions.join(game,teamAccessCode(game.id,'team-1'));expect(()=>sessions.join(game,'WRONG')).toThrow(/not valid/);expect(()=>sessions.require(joined.token,game.id,'team-2')).toThrow(/not authorized/);});
 it('assigns a non-colliding persisted team identity when another game already uses team-1',()=>{const repo=new MemoryGameRepository(),service=new SimulationService(repo),first=service.create(['First']),second=service.create(['Second']);expect(first.teams[0].id).toBe('team-1');expect(second.teams[0].id).not.toBe('team-1');expect(service.get(second.id).teams[0].name).toBe('Second');});
 it('does not auto-select newest game or first team',()=>{const source=readFileSync('src/web/App.tsx','utf8');expect(source).not.toContain('games.find');expect(source).not.toContain('teams[0].id');expect(source).toContain('Enter your team workspace');});
 it('enforces ownership on every team-specific route',()=>expect(readFileSync('src/server/index.ts','utf8').match(/authorize\(q\)/g)).toHaveLength(4));
});
describe('Phase 5 discoverability and instructor view',()=>{
 it('shows a neutral People signal without coaching or gates',()=>{const source=readFileSync('src/web/components/StudentDashboardV6.tsx','utf8');expect(source).toContain('People · ${view.stakeholders.length} available');expect(source).not.toMatch(/Talk to Kubiak|Ask Sylvia|contact Reyes|disclosure gate/i);});
 it('orders instructor teams by name rather than outcome',()=>expect(instructorProjection(createGame({teamNames:['Zulu','Alpha','Middle'],config:cloneConfig()})).teams.map(t=>t.name)).toEqual(['Alpha','Middle','Zulu']));
 it('preserves original stakeholder turns by team and stakeholder',()=>{const game=createGame({teamNames:['T'],config:cloneConfig()}),team=game.teams[0];team.transcripts.push({id:'x',gameId:game.id,teamId:team.id,round:1,actorType:'stakeholder',actorId:'ntende',userMessage:'Our exact question?',actorReply:'Her exact answer.',timestamp:'2026-09-10T00:00:00Z',contextHash:'x'});const transcript=instructorProjection({...game,teams:[team]}).teams[0].transcripts[0];expect([transcript.userMessage,transcript.actorReply]).toEqual(['Our exact question?','Her exact answer.']);});
 it('has no leaderboard or outcome-based ordering',()=>expect(readFileSync('src/web/components/InstructorDashboard.tsx','utf8')).not.toMatch(/leaderboard|rank number|sort.*outcome|sort.*benefit/i));
});
