import {readFileSync} from 'node:fs';import {describe,expect,it} from 'vitest';import {SimulationService} from '../src/application/service.js';import {closeRound} from '../src/domain/engine.js';import {MemoryGameRepository} from '../src/persistence/repository.js';
const r1={opening_posture:'pause_pilot',savings_commitment_made:false,savings_commitment_usd:null,memo_handling:'not_found'};
describe('Phase 5 instructor-controlled round release',()=>{
 it('marks every unreleased future round locked and non-actionable',()=>{const source=readFileSync('src/web/components/Shell.tsx','utf8');expect(source).toContain('locked=number>round');expect(source).toContain('aria-disabled={locked}');expect(source).toContain("<small>Locked</small>");expect(source).not.toMatch(/<button[^>]*className=\{`round-link/);});
 it('shows the exact instructor-release message after submission',()=>{const source=readFileSync('src/web/App.tsx','utf8');expect(source).toContain('Round {student.game.activeRound} submitted. Round {student.game.activeRound+1} opens when your instructor releases it.');});
 it('uses the existing release path rather than adding a competing progression route',()=>{const server=readFileSync('src/server/index.ts','utf8'),service=readFileSync('src/application/service.ts','utf8');expect(server.match(/\/close'/g)).toHaveLength(1);expect(service).toContain('closeRound(this.get(gameId))');});
 it('labels the selected-game control with the next round and waits for every team',()=>{const source=readFileSync('src/web/components/InstructorDashboard.tsx','utf8');expect(source).toContain('Release Round ${nextRound}');expect(source).toContain('allSubmitted');});
 it('releases the next round for all teams in the selected game',()=>{const repo=new MemoryGameRepository(),service=new SimulationService(repo),game=service.create(['A','B']);for(const team of game.teams)service.submit(game.id,team.id,r1,'member');const released=service.close(game.id);expect(released.activeRound).toBe(2);expect(released.teams.every(t=>t.results.some(r=>r.round===1))).toBe(true);});
 it('does not affect teams in another game',()=>{const repo=new MemoryGameRepository(),service=new SimulationService(repo),selected=service.create(['A']),other=service.create(['B']);service.submit(selected.id,selected.teams[0].id,r1,'member');service.close(selected.id);expect(service.get(other.id)).toEqual(other);});
 it('is exactly the existing closeRound transition with no special outcome mutation',()=>{const repo=new MemoryGameRepository(),service=new SimulationService(repo),game=service.create(['A']);service.submit(game.id,game.teams[0].id,r1,'member');const before=service.get(game.id),expected=closeRound(before),actual=service.close(game.id);expect(actual).toEqual(expected);expect(actual.teams[0].currentState.outcome).toBeUndefined();});
});
