import {afterEach,describe,expect,it} from 'vitest';
import {isolatedPostgres,postgresEnabled} from './helpers/postgres.js';
import {r1} from './helpers/postgres-paths.js';
import {PersistentSimulationService} from '../src/application/persistent-service.js';
import {SimulationService} from '../src/application/service.js';

describe.skipIf(!postgresEnabled)('PostgreSQL aggregate concurrency (separate pools)',()=>{
 let db:Awaited<ReturnType<typeof isolatedPostgres>>|undefined;
 afterEach(async()=>{await db?.close();db=undefined;});
 async function setup(){db=await isolatedPostgres();const a=new PersistentSimulationService(db.repo),b=new PersistentSimulationService(db.peer()),game=await a.create(['One','Two']);return {a,b,game};}
 it('serializes create-time team-ID allocation',async()=>{db=await isolatedPostgres();const a=new PersistentSimulationService(db.repo),b=new PersistentSimulationService(db.peer());const games=await Promise.all([a.create(['A','B']),b.create(['C','D'])]);const ids=games.flatMap(g=>g.teams.map(t=>t.id));expect(new Set(ids).size).toBe(4);expect(await a.list()).toHaveLength(2);});
 it('keeps concurrent evidence, document versions and another team isolated',async()=>{const {a,b,game}=await setup(),id=game.teams[0].id;await Promise.all([a.evidence(game.id,id,'analyst_memo'),b.evidence(game.id,id,'doug_board_deck',{versionId:'v3'}),a.evidence(game.id,id,'article_14')]);const loaded=await a.get(game.id);expect(loaded.teams[0].currentState.evidence.analyst_memo.accessed).toBe(true);expect(loaded.teams[0].currentState.evidence.doug_board_deck.accessedVersions).toEqual(['v3']);expect(loaded.teams[0].currentState.evidence.article_14.accessed).toBe(true);expect(loaded.teams[1].currentState.evidence.doug_board_deck.accessed).toBe(false);});
 it('retains both concurrent conversation turns and their context hashes',async()=>{const {a,b,game}=await setup(),id=game.teams[0].id;const turns=await Promise.all([a.converse(game.id,id,{actorType:'advisor',actorId:'marchetti',message:'What is missing?'}),b.converse(game.id,id,{actorType:'advisor',actorId:'marchetti',message:'We observed the desk.'})]);expect((await a.get(game.id)).teams[0].transcripts).toEqual(expect.arrayContaining(turns));expect((await a.get(game.id)).teams[0].transcripts).toHaveLength(2);});
 it('retains different teams submitting simultaneously',async()=>{const {a,b,game}=await setup();await Promise.all([a.submit(game.id,game.teams[0].id,r1,'one'),b.submit(game.id,game.teams[1].id,r1,'two')]);const loaded=await a.get(game.id);expect(loaded.teams.map(t=>t.submissions.length)).toEqual([1,1]);expect((await a.close(game.id)).activeRound).toBe(2);});
 it('accepts exactly one duplicate submission without replacing the winner',async()=>{const {a,b,game}=await setup();const results=await Promise.allSettled([a.submit(game.id,game.teams[0].id,r1,'one'),b.submit(game.id,game.teams[0].id,r1,'two')]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(results.filter(r=>r.status==='rejected')).toHaveLength(1);expect((await a.get(game.id)).teams[0].submissions).toHaveLength(1);});
 it('does not lose corrections when evidence is opened concurrently',async()=>{const {a,b,game}=await setup(),id=game.teams[0].id;await a.submit(game.id,id,r1,'original');const before=(await a.get(game.id)).teams[0].submissions[0];await Promise.all([a.correct(game.id,id,{...r1,opening_posture:'continue_clearpath'},{actor:'instructor',round:1}),b.evidence(game.id,id,'doug_board_deck',{versionId:'v3'})]);const team=(await a.get(game.id)).teams[0];expect(team.submissions[0]).toMatchObject({id:before.id,submitter:'original',submittedAt:before.submittedAt});expect(team.submissions[0].corrections).toHaveLength(1);expect(team.currentState.evidence.doug_board_deck.accessedVersions).toEqual(['v3']);});
 it('does not release the same submitted round twice',async()=>{const {a,b,game}=await setup();for(const team of game.teams)await a.submit(game.id,team.id,r1,'student');const result=await Promise.allSettled([a.close(game.id),b.close(game.id)]);expect(result.filter(x=>x.status==='fulfilled')).toHaveLength(1);const loaded=await a.get(game.id);expect(loaded.activeRound).toBe(2);expect(loaded.teams.every(t=>t.results.length===1)).toBe(true);});
 it('serializes confirmed missing-team overrides and rejects stale actions',async()=>{const {a,b,game}=await setup();await a.submit(game.id,game.teams[0].id,r1,'student');const action={actor:'instructor' as const,round:1 as const,confirmed:true as const,outstandingTeamIds:[game.teams[1].id]};const results=await Promise.allSettled([a.override(game.id,action),b.override(game.id,action)]);expect(results.filter(x=>x.status==='fulfilled')).toHaveLength(1);const loaded=await a.get(game.id);expect(loaded.activeRound).toBe(2);expect(loaded.teams[1].submissions).toHaveLength(1);expect(loaded.teams[1].submissions[0].kind).toBe('non_submission');});
 it('holds the game lock across an awaited operation and merges the next request',async()=>{
  const {a,b,game}=await setup();let entered!:()=>void,release!:()=>void;
  const ready=new Promise<void>(resolve=>{entered=resolve;}),gate=new Promise<void>(resolve=>{release=resolve;});
  const first=db!.repo.withGame(game.id,async snapshot=>{entered();await gate;new SimulationService(snapshot).evidence(game.id,game.teams[0].id,'analyst_memo');});
  await ready;let settled=false;const second=b.evidence(game.id,game.teams[0].id,'doug_board_deck',{versionId:'v3'}).finally(()=>{settled=true;});
  try{await new Promise(resolve=>setTimeout(resolve,40));expect(settled).toBe(false);}finally{release();}
  await Promise.all([first,second]);const e=(await a.get(game.id)).teams[0].currentState.evidence;expect(e.analyst_memo.accessed).toBe(true);expect(e.doug_board_deck.accessedVersions).toEqual(['v3']);
 });
 it('rolls back a failed callback and releases the lock for the next request',async()=>{const {a,b,game}=await setup();await expect(db!.repo.withGame(game.id,snapshot=>{new SimulationService(snapshot).evidence(game.id,game.teams[0].id,'analyst_memo');throw new Error('intentional failure');})).rejects.toThrow('intentional failure');expect((await a.get(game.id)).teams[0].currentState.evidence.analyst_memo.accessed).toBe(false);await b.evidence(game.id,game.teams[0].id,'analyst_memo');expect((await a.get(game.id)).teams[0].currentState.evidence.analyst_memo.accessed).toBe(true);});
});
