import {isSemanticNull} from './schemas.js';
import type {AdvisorId,AdvisorStance,AdvisorValence,BpmConfig,RoundNumber,RoundSubmission,TeamState} from './types.js';

const clamp01=(n:number)=>Math.max(0,Math.min(1,n));
const current=(round:RoundNumber,p:Record<string,unknown>,subs:RoundSubmission[],wanted:RoundNumber,key:string)=>round===wanted?p[key]:subs.find(x=>x.round===wanted)?.payload[key];
const valence=(score:number):AdvisorValence=>score>.72?'support':score<.45?'oppose':'mixed';
const stance=(advisor:AdvisorId,score:number,intensity:number,rationale_tags:string[],focus_lever:string|null,components:Record<string,number>,renderContext:Record<string,unknown>={}):AdvisorStance=>({advisor,valence:valence(score),intensity:clamp01(intensity),rationale_tags,focus_lever,components,renderContext});
const largestGap=(items:Array<[string,number]>)=>items.sort((a,b)=>a[1]-b[1])[0]?.[0]??null;
const substantive=(v:unknown)=>!isSemanticNull(v)&&!(typeof v==='string'&&/^(placeholder|to be determined)$/i.test(v.trim()));

export function scoreMarchetti(round:RoundNumber,p:Record<string,unknown>,s:TeamState,subs:RoundSubmission[]):AdvisorStance{
 const required=round===3?20:round===4?45:60,evidence=clamp01((s.scalars.discovery_depth??0)/required),constraint=Boolean(current(round,p,subs,3,'constraint_claim')),root=Boolean(current(round,p,subs,4,'root_cause_claim'));let altitude=1;
 if(round===3&&!constraint)altitude=0;if(round===4&&!root)altitude=constraint?.5:0;if(round>=5&&!(constraint&&root))altitude=constraint||root?.5:0;
 const ambition=String(current(round,p,subs,5,'redesign_ambition')??''),depth=String(current(round,p,subs,6,'automation_depth')??''),instability=ambition&&depth?(({refine:{A:0,B:.15,C:.45,D:.7},redesign_structure_intact:{A:.2,B:0,C:.15,D:.35},clean_sheet:{A:.6,B:.35,C:.15,D:0}} as Record<string,Record<string,number>>)[ambition]?.[depth]??0):0,sequence=1-instability,baseScore=.95*evidence+.05*sequence,score=altitude<1?Math.min(baseScore,.4):baseScore;
 return stance('marchetti',score,Math.abs(score-.6)/.6,['evidence_term','altitude_term','sequence_term'],largestGap([['discovery_depth',evidence],['analytical_level',altitude],['scope_sequence',sequence]]),{evidence,altitude,sequence,score});
}

export function scoreOyelaran(round:RoundNumber,p:Record<string,unknown>,_s:TeamState,subs:RoundSubmission[]):AdvisorStance{
 if(round===9)return {...stance('oyelaran',.6,.2,['prior_question_unanswered'],null,{score:.6}),valence:'mixed'};
 if(round>=2&&round<=5)return {...stance('oyelaran',.6,.1,['automation_not_open'],null,{score:.6}),valence:'mixed'};
 if(round===1)return {...stance('oyelaran',.6,.2,['inherited_pilot_parameters'],null,{score:.6}),valence:'mixed'};
 const depth=String(current(round,p,subs,6,'automation_depth')??'A'),ps=(current(round,p,subs,6,'parameter_set')??{}) as Record<string,unknown>,answered=[substantive(ps.threshold_usd)&&substantive(ps.threshold_owner),substantive(ps.change_detection),substantive(ps.queue_owner_and_authority),substantive(ps.rollback_trigger),substantive(ps.patient_escalation_path)],parameters=answered.filter(Boolean).length/5,constraintClaim=(current(round,p,subs,3,'constraint_claim')??{}) as Record<string,unknown>,automated= current(round,p,subs,6,'automates_authorization')===true?'authorization':'verification',constraint=String(constraintClaim.station??''),constraintTerm=automated===constraint?1:.7,score=(.5+.5*parameters)*constraintTerm,feasibility=({A:1,B:.9,C:.75,D:.5} as Record<string,number>)[depth]??1;
 const base=stance('oyelaran',score,Math.abs(score-.6)/.6,['parameter_completeness',constraintTerm===1?'constraint_aligned':'constraint_misaligned'],parameters<1?'parameter_set':constraintTerm<1?'automated_station':null,{parameters,constraint:constraintTerm,score},{feasibility,depth});
 return parameters<.4&&['C','D'].includes(depth)?{...base,valence:'oppose',intensity:.9,rationale_tags:[...base.rationale_tags,'high_depth_low_parameters']}:base;
}

export function scoreCastellanos(round:RoundNumber,p:Record<string,unknown>,s:TeamState,subs:RoundSubmission[],c:BpmConfig):AdvisorStance{
 const ids=['walters','ferrara','boyce','ntende'] as const,room=(current(round,p,subs,5,'design_room')??[]) as string[],actions=(current(round,p,subs,7,'coalition_actions')??[]) as string[],allocation=(current(round,p,subs,2,'discovery_allocation')??{}) as Record<string,number>,scope=String(current(round,p,subs,2,'discovery_scope')??''),ownership=String(current(round,p,subs,5,'process_ownership')??''),moved=(id:typeof ids[number])=>s.stakeholders[id].trust!==c.stakeholders[id].trust||s.stakeholders[id].position!==c.stakeholders[id].position,contactedIds=ids.filter(id=>moved(id)||(id==='walters'?room.includes('union')||actions.includes('walters_negotiated_path'):id==='ferrara'?Number(allocation.floor_observation??0)>0||room.includes('frontline_staff'):id==='boyce'?scope.includes('denials')||room.includes('frontline_staff'):ownership==='ntende'||actions.includes('ntende_public_ownership'))),contacted=contactedIds.length/4,positions=contactedIds.map(id=>s.stakeholders[id].position),executor=positions.length?positions.reduce((a,b)=>a+b,0)/positions.length/100:.5,participation=([room.includes('frontline_staff'),room.includes('union')].filter(Boolean).length/2)*.6+Math.min(actions.length,4)/4*.4,approach=String(current(round,p,subs,7,'implementation_approach')??'pilot_single_site'),training=Number(((current(round,p,subs,7,'budget_allocation')??{}) as Record<string,unknown>).training??0),noticeLate=!room.includes('union'),compression=clamp01((approach==='system_wide'?.5:approach==='phase_by_function'?.2:0)+(training<c.readiness.trainingFullCreditUsd?.25:0)+(noticeLate?.25:0)),timing=1-compression,score=.3*contacted+.2*executor+.3*participation+.2*timing,lowest=positions.length?contactedIds[positions.indexOf(Math.min(...positions))]:null,intensity=contactedIds.length===0?.3:1-Math.min(...positions)/100;
 return stance('castellanos',score,intensity,[contactedIds.length?`lowest_executor_${lowest}`:'no_executors_contacted',...(round>=8?['forward_only']:[])],largestGap([['executor_contact',contacted],['executor_position',executor],['participation',participation],['implementation_timing',timing]]),{contacted,executor,participation,timing,score});
}

export function scoreBrennan(round:RoundNumber,p:Record<string,unknown>,s:TeamState,subs:RoundSubmission[]):AdvisorStance{
 if(round<3)return {...stance('brennan',.6,1/3,['baseline_absent'],'published_baseline',{score:.6}),valence:'mixed'};
 const claim=Number(((current(round,p,subs,10,'board_narrative')??{}) as Record<string,unknown>).claimed_benefit_usd??current(round,p,subs,1,'savings_commitment_usd')??0),defensible=s.scalars.defensible_benefit_usd??(String(current(round,p,subs,3,'published_baseline'))==='restate_documented'?claim:claim*.53),claimSupport=1-Math.max(0,Math.min(claim-defensible,claim))/Math.max(claim,1),baseline=String(current(round,p,subs,3,'published_baseline')??''),category=baseline==='adopt_inherited'?.4:1,r7=(current(round,p,subs,7,'budget_allocation')??{}) as Record<string,unknown>,costItems=[substantive(r7.training),substantive(r7.contingency_reserve),Boolean(current(round,p,subs,8,'cutover_controls')),Boolean(current(round,p,subs,10,'sustainment'))],cost=costItems.filter(Boolean).length/costItems.length;let score=.5*claimSupport+.25*category+.25*cost;const constraint=(current(round,p,subs,3,'constraint_claim')??{}) as Record<string,unknown>;if(round===3&&constraint.station==='authorization'&&baseline==='adopt_inherited')score*=.35;const unresolved=[claimSupport<1,category<1,cost<1].filter(Boolean).length;
 return stance('brennan',score,unresolved/3,['claim_support','category_discipline','cost_complete'],largestGap([['claimed_benefit_usd',claimSupport],['published_baseline',category],['cost_completeness',cost]]),{claimSupport,category,cost,score,unresolvedQuestions:unresolved});
}

export function scoreKowalczyk(round:RoundNumber,p:Record<string,unknown>,s:TeamState,subs:RoundSubmission[],c:BpmConfig):AdvisorStance{
 if((s.scalars.discovery_depth??0)<50)return {...stance('kowalczyk',.6,.15,['insufficient_visibility'],null,{score:.6},{renderDepth:'moment'}),valence:'mixed'};
 const room=(current(round,p,subs,5,'design_room')??[]) as string[],ps=(current(round,p,subs,6,'parameter_set')??{}) as Record<string,unknown>,approach=String(current(round,p,subs,7,'implementation_approach')??''),training=Number(((current(round,p,subs,7,'budget_allocation')??{}) as Record<string,unknown>).training??0),sustainment=(current(round,p,subs,10,'sustainment')??[]) as string[],addressed=(key:string)=>({change_detection:substantive(ps.change_detection),monitoring_metrics:sustainment.includes('monitoring_metrics'),frontline_participation:room.includes('frontline_staff'),queue_authority:substantive(ps.queue_owner_and_authority),training_and_phasing:training>=c.readiness.trainingFullCreditUsd&&approach!=='system_wide',phase_by_function:approach==='phase_by_function',named_process_owner:String(current(round,p,subs,5,'process_ownership'))!=='unassigned'} as Record<string,boolean>)[key]??false,facts=c.advisors.operationalFacts.filter(x=>addressed(x.addressedBy)).length/c.advisors.operationalFacts.length,eliminations=room.includes('frontline_staff')?1:2,unexplained=room.includes('frontline_staff')?0:1,workaround=1-unexplained/Math.max(eliminations,1),authorityGaps=[ps.queue_owner_and_authority,ps.threshold_owner].filter(isSemanticNull).length,executionLoad=clamp01(1-authorityGaps/2-(approach==='system_wide'?.2:0)),score=.45*facts+.3*workaround+.25*executionLoad;
 return stance('kowalczyk',score,1-score,['facts_addressed','workaround_term','execution_load',`render_depth_${score<.45?'shift':score<.72?'sequence':'moment'}`],largestGap([['operational_facts',facts],['workaround_treatment',workaround],['execution_load',executionLoad]]),{facts,workaround,executionLoad,score});
}

export function scoreOkonkwo(round:RoundNumber,p:Record<string,unknown>,s:TeamState,subs:RoundSubmission[],c:BpmConfig):AdvisorStance{
 const approach=String(current(round,p,subs,7,'implementation_approach')??''),duration=c.durations[approach]??70,pace=clamp01(1-duration/210),showable=Boolean(current(round,p,subs,3,'constraint_claim')||current(round,p,subs,5,'redesign_ambition')||current(round,p,subs,8,'go_decision')),visibility=showable?1:.3,ambition=({refine:.35,redesign_structure_intact:.7,clean_sheet:1} as Record<string,number>)[String(current(round,p,subs,5,'redesign_ambition'))]??.3,score=.45*pace+.35*visibility+.2*ambition,confidence=s.scalars.sponsor_confidence??50,tags=['pace','visibility','ambition'];if(confidence>80)tags.push('escalation');const base=stance('okonkwo',score,Math.abs(score-.6)/.6,tags,largestGap([['implementation_approach',pace],['showable_output',visibility],['redesign_ambition',ambition]]),{pace,visibility,ambition,score},{suppressOffers:confidence<40,shortRender:confidence<40});
 if(round===7&&(s.scalars.readiness??0)>75&&approach==='system_wide')return {...base,valence:'oppose',rationale_tags:[...base.rationale_tags,'phase_it']};const responses=(current(round,p,subs,9,'crisis_responses')??{}) as Record<string,{disclosure?:string}>;if(round===9&&Object.values(responses).some(x=>['none','okonkwo_only'].includes(x.disclosure??'')))return {...base,valence:'oppose',rationale_tags:[...base.rationale_tags,'disclose_faster']};return base;
}

export function scoreAdvisors(round:RoundNumber,p:Record<string,unknown>,s:TeamState,subs:RoundSubmission[],c:BpmConfig):AdvisorStance[]{return [scoreMarchetti(round,p,s,subs),scoreOyelaran(round,p,s,subs),scoreCastellanos(round,p,s,subs,c),scoreBrennan(round,p,s,subs),scoreKowalczyk(round,p,s,subs,c),scoreOkonkwo(round,p,s,subs,c)];}
