import {createHash} from 'node:crypto';import type {BpmConfig,RiskId} from './types.js';
const riskOrder:RiskId[]=['statement_4_17','duplicate_posting','silent_field_change','grievance','freeze_collision','restatement','clinical_revolt','vendor_cliff'];
const crisis=(benefitUsd:number,scalars:Record<string,number>={},stakeholders:Record<string,Record<string,number>>={},delayDays=0)=>({benefitUsd,scalars,stakeholders,delayDays});
export const defaultConfig:BpmConfig={version:'bpm-v1',scenarioVersion:'bpm-v1',unresolved:{},
scalar:{sponsor_confidence:{init:62,drift:-1,min:0,max:100},board_credibility:{init:48,drift:0,min:0,max:100},financial_credibility:{init:50,drift:.5,min:0,max:100},discovery_depth:{init:0,drift:0,min:0,max:100},readiness:{init:null,drift:0,min:0,max:100},automation_risk_debt:{init:18,drift:0,min:0,max:100},technical_partnership:{init:32,drift:0,min:0,max:100},realized_benefit_usd:{init:null,drift:0,min:0,max:null},defensible_benefit_usd:{init:null,drift:0,min:0,max:null}},stakeholders:{ntende:{trust:30,position:35},deiss:{trust:50,position:58},moreau:{trust:45,position:30},kubiak:{trust:28,position:50},anand:{trust:55,position:60},walters:{trust:50,position:45},ferrara:{trust:62,position:8},boyce:{trust:58,position:12},reyes:{trust:40,position:50}},disclosureGates:{reyes:{condition:'contacted',calendarEntry:false}},stations:['scheduling','registration','verification','authorization','financial_clearance','claim_submission','denial_management'],
discovery:{yields:{document_analysis:8,structured_interviews:20,process_mining:20,floor_observation:30},scopeMultipliers:{denials_only:1.15,denials_through_auth:1,full_front_end:.85},scopeCoverage:{denials_only:.45,denials_through_auth:.72,full_front_end:1}},readiness:{weights:{designQuality:.15,executorPosition:.30,frontline:.20,training:.25},trainingFullCreditUsd:700000,discoveryMultiplier:{min:.6,max:1,interpolation:'linear'}},automationMultipliers:{A:.3,B:.7,C:1,D:1.2},automationDebt:{inherited:18,missing:{thresholdGovernance:14,changeDetection:16,queueOwnership:13,rollbackTrigger:12,patientEscalation:15}},budget:{initialRemainingUsd:2800000,controlCosts:{command_center:240000,parallel_running:400000,manual_fallback:160000,rollback_capability:320000},sustainmentCosts:{named_process_owner:180000,monitoring_metrics:120000,exception_review_cadence:90000,change_governance:160000},metricRebuildCost:85000,unfundedRollbackCost:175000},
risks:{selection:{first:40,second:60},canonicalOrder:riskOrder,financialCredibilityBands:[{min:60,points:0},{min:45,points:5},{min:30,points:10},{min:0,points:15}],authorizationAutomation:{A:0,B:5,C:10,D:15},sourcingMultiplier:{retain_internal:0,cosource_denials:1,full_bpo:1.5},restatement:{commitmentGapFullScaleUsd:12000000,supportedBenefitCell:{ambition:'redesign_structure_intact',depth:'B'}}},benefits:{baseMatrix:{refine:{A:4500000,B:6800000,C:9200000,D:10800000},redesign_structure_intact:{A:5600000,B:8500000,C:11800000,D:13500000},clean_sheet:{A:6000000,B:9500000,C:13000000,D:15000000}},readinessFactor:{min:.5,max:1},crisisDamage:{statement_4_17:crisis(650000,{board_credibility:-18,sponsor_confidence:-12},{moreau:{position:-30},anand:{position:-35}}),duplicate_posting:crisis(1100000,{board_credibility:-30,financial_credibility:-25,sponsor_confidence:-15},{deiss:{position:-28}}),silent_field_change:crisis(1600000,{technical_partnership:-15,sponsor_confidence:-18},{moreau:{position:-24},anand:{position:-20}}),grievance:crisis(1300000,{sponsor_confidence:-20},{walters:{trust:-30,position:-35}},21),freeze_collision:crisis(900000,{technical_partnership:-22,sponsor_confidence:-14,readiness:-12},{},11),restatement:crisis(400000,{board_credibility:-40,sponsor_confidence:-30,financial_credibility:-20}),clinical_revolt:crisis(2300000,{sponsor_confidence:-22},{moreau:{position:-40},anand:{position:-45}},28),vendor_cliff:crisis(1700000,{sponsor_confidence:-12,financial_credibility:-12},{},18)},credibilityFactor:{financialWeight:.55,boardWeight:.45,minimum:.45,baselineMethod:{restate_documented:1,publish_range:.92,defer:.8,adopt_inherited:.68}},sustainmentRetention:[.55,.68,.8,.91,1],triumphSeverityThreshold:55,materialRelationshipDamage:20,substantialDefensibilityRatio:.75},
benefitReview:{lowerBasisBands:{substantialMaxRatio:.3,peakMinRatio:.6,substantialScore:.3,lowScore:.6},figureChangeThresholdPercent:15,unexplainedChangeBoardCredibilityPenalty:10},advisors:{coefficients:{marchetti:{evidence:.45,sequence:.35,scope:.2},oyelaran:{feasibility:.35,completeness:.45,constraint:.2},castellanos:{executor:.4,participation:.35,timing:.25},brennan:{claim:.5,category:.25,cost:.25},kowalczyk:{specificity:.45,workaround:.3,load:.25},okonkwo:{pace:.45,visibility:.3,ambition:.25}},bands:{strongSupport:.55,support:.2,oppose:-.2,strongOppose:-.55},oyelaranInteractionPenalty:.3,kowalczykLowDiscoveryMultiplier:.6,okonkwoLowConfidenceMultiplier:.7,okonkwoHighConfidenceMultiplier:1.15,operationalFacts:[
{id:'weekend_feed',description:'Eligibility data is stale over weekends.',addressedBy:'change_detection',discoveryPath:'ask_it_process_question'},
{id:'renewal_90_days',description:'Two payers require authorization renewal at ninety days.',addressedBy:'monitoring_metrics',discoveryPath:'authorization_observation'},
{id:'optional_reject_field',description:'The clearinghouse rejects a field marked optional.',addressedBy:'change_detection',discoveryPath:'process_mining'},
{id:'payer_plan_card',description:'A routing card bypasses unreliable payer-plan combinations.',addressedBy:'frontline_participation',discoveryPath:'floor_observation'},
{id:'after_shift_queue',description:'Three representatives work exceptions after shift.',addressedBy:'queue_authority',discoveryPath:'end_of_day_question'},
{id:'insurance_rekey',description:'Registration staff re-key visible insurance data.',addressedBy:'frontline_participation',discoveryPath:'floor_observation'},
{id:'second_verification',description:'A second check exists after a six-figure error.',addressedBy:'frontline_participation',discoveryPath:'ask_why_rekey'},
{id:'monday_spike',description:'Authorization volume doubles Mondays and after holidays.',addressedBy:'training_and_phasing',discoveryPath:'capacity_observation'},
{id:'shared_counselor',description:'Two east-side hospitals share one financial counselor.',addressedBy:'phase_by_function',discoveryPath:'full_front_end_observation'},
{id:'month_end_analysts',description:'Month-end close removes two analysts for three days.',addressedBy:'named_process_owner',discoveryPath:'denials_bench'}]},attention:{total:100,containment:{let_run:0,contain_narrow:25,contain_broad:55,halt_process:70},disclosure:{none:0,okonkwo_only:5,executive_team:10,board_proactive:20,public:30},rollback:{funded:20,unfunded:40}},crisisResponse:{containmentMultiplier:{let_run:1.2,contain_narrow:.9,contain_broad:.65,halt_process:.5},rollbackMultiplier:{funded:.75,unfunded:.85},disclosureCredibilityMultiplier:{none:1.15,okonkwo_only:1.05,executive_team:.95,board_proactive:.8,public:1}},durations:{pilot_single_site:28,phase_by_function:42,system_wide:14},calendar:{implementationStart:'2026-09-14',unionNoticeDays:60,epicFreezeStart:'2026-10-19',fiscalYearDeadline:'2026-12-31'},claimScoring:{constraintWeights:{location:.3,arithmetic:.25,implication:.45},rootCauseWeights:{component:.55,proportionality:.45},benefitReviewWeights:{disclosure:.5,basis:.3,type:.2}}};
// 0.68 allowed the theoretical maximum inherited-baseline path to clear $8M.
// 0.53 is the smallest two-decimal reduction preserving the arithmetic invariant.
defaultConfig.benefits.credibilityFactor.baselineMethod.adopt_inherited=.53;
export const cloneConfig=(config:BpmConfig=defaultConfig):BpmConfig=>structuredClone(config);const canonical=(value:unknown):string=>{if(Array.isArray(value))return `[${value.map(canonical).join(',')}]`;if(value&&typeof value==='object')return `{${Object.keys(value as object).sort().map(k=>`${JSON.stringify(k)}:${canonical((value as Record<string,unknown>)[k])}`).join(',')}}`;return JSON.stringify(value)};export const configHash=(config:BpmConfig):string=>createHash('sha256').update(canonical(config)).digest('hex');
