export const evidenceLibrary=[
 {id:'clearpath_context',title:'Project Clearpath briefing',availableRound:1,condition:'always',studentContent:'Clearpath is fourteen months old. The approved budget was $9M; $6.2M has been spent. The pilot covers eligibility verification for two payers.',hiddenMetadata:{}},
 {id:'analyst_memo',title:'Internal analyst memo',availableRound:1,condition:'inherited_files',studentContent:'A four-page internal note questions whether Clearpath is working at the correct process level. Its conclusions require independent verification.',hiddenMetadata:{partialTruth:true}},
 {id:'baseline_figures',title:'Inherited operating baseline',availableRound:1,condition:'always',studentContent:'Denials 11.4%; days in A/R 58; cost to collect 4.2%; authorization turnaround 4.3 days; 22% of procedures delayed or rescheduled.',hiddenMetadata:{}},
 {id:'calendar',title:'Program calendar',availableRound:1,condition:'always',studentContent:'The board date is seven months away. An Epic change freeze covers Weeks 7–9. Material job-classification changes require sixty days notice.',hiddenMetadata:{}},
 {id:'clearpath_all',title:'CLEARPATH_ALL',availableRound:1,condition:'always',studentContent:'Inherited project folder. The folder reports 63 documents.',hiddenMetadata:{}},
 {id:'doug_board_deck',title:"Doug's board presentation",availableRound:1,condition:'always',studentContent:'BOARD_Q2_CLEARPATH_FINAL_v4.pptx. File properties include version history.',hiddenMetadata:{}},
 {id:'article_14',title:'Article 14 contract language',availableRound:1,condition:'always',studentContent:'Article 14 begins on page 41 of CBA_2024_2027.pdf.',hiddenMetadata:{}},
 {id:'ferrara_cheat_sheet',title:'Front-desk working aid',availableRound:2,condition:'floor_observation',studentContent:'A frontline routing aid records payer-plan exceptions used during registration.',hiddenMetadata:{owner:'ferrara'}},
 {id:'boyce_database',title:'Denials analyst shadow database',availableRound:2,condition:'denials_engagement',studentContent:'An analyst-maintained dataset links denial patterns to operational work.',hiddenMetadata:{owner:'boyce'}},
 {id:'stale_weekend_feed',title:'Eligibility interface condition',availableRound:2,condition:'technical_partnership',studentContent:'The eligibility feed is stale over weekends; Monday registrations use Friday data.',hiddenMetadata:{owner:'kubiak'}},
 {id:'capacity_evidence',title:'Capacity and arrival evidence',availableRound:3,condition:'always',studentContent:'Capacity, input, and output observations are available across the authoritative six-station Week 3 process map.',hiddenMetadata:{designedConstraint:'authorization',targetShortfall:91}},
 {id:'vendor_presentation',title:'Week 6 vendor presentation',availableRound:6,condition:'always',studentContent:'Fifteen-slide incumbent platform presentation.',hiddenMetadata:{}},
 {id:'readiness_assessment',title:'Readiness assessment',availableRound:7,condition:'always',studentContent:'Fourteen-page readiness assessment prepared by Y. Castellanos.',hiddenMetadata:{}},
 {id:'operational_facts',title:'Operational conditions notebook',availableRound:4,condition:'discovery',studentContent:'Observed exception work, payer changes, staffing patterns, and workaround conditions collected during discovery.',hiddenMetadata:{facts:['weekend_feed','renewal_90_days','optional_reject_field','unpaid_exception_queue','rekeying','redundant_verification','monday_spike','shared_counselor','month_end_analysts']}}
] as const;
export type EvidenceId=typeof evidenceLibrary[number]['id'];
