import type {BpmConfig,RiskId,RoundNarrativeSnapshot,RoundNumber,RoundSubmission,TeamState} from './types.js';

type Candidate={id:string;conditionId:string;matches:(state:TeamState,submissions:RoundSubmission[])=>boolean;text:string};
type RoundContent={base:string;variants?:Candidate[];defaultId?:string;defaultText?:string};
const prior=(submissions:RoundSubmission[],round:RoundNumber,key:string)=>submissions.find(x=>x.round===round)?.payload[key];
const has=(submissions:RoundSubmission[],round:RoundNumber,key:string,value:string)=>((prior(submissions,round,key)??[]) as string[]).includes(value);

const crisisText:Record<RiskId,string>={
 statement_4_17:`Tuesday, 11:20 a.m. A woman named Dana Whitfield posted a photograph of a Regional Health Partners letter. It says that an outstanding balance of $4.17 has been referred to a collection agency and may affect her credit. Her son was treated for acute lymphoblastic leukemia across nineteen months. The family has paid $31,400 out of pocket. By lunch the post has been shared four thousand times. The letter is correct: a secondary-payer adjustment left $4.17, it aged past 120 days, and blank in the ruleset meant zero. By Wednesday a television reporter has called twice.`,
 duplicate_posting:`Monday, 4:40 p.m. A staff accountant notices that daily cash posting is $2.3 million higher than the deposit. The remittance file processed twice on Thursday and nobody noticed for four days because the old manual reconciliation was not rebuilt. Roughly eleven hundred patient accounts now show money they do not owe; forty-one refund checks have been mailed. The number given to Okonkwo on Friday included the duplicate, and Deiss has asked in writing whether last week's figure was reported on the same basis.`,
 silent_field_change:`Wednesday, 9:15 a.m. The denials batch returns with 340 procedures across eleven days lacking valid authorization. A payer moved a portal field. The bot kept submitting and the portal kept acknowledging receipt, but receipt was never approval. Some procedures have happened; others are scheduled next week. The freeze is running. A scheduler named Renee starts calling patients from the top of the list without being told.`,
 grievance:`Monday, 8:00 a.m. SEIU files on Article 14. By 10:00 registration is working to rule. Everyone is present and performing every documented step exactly as written. Registration time rises from six minutes to fourteen and the authorization queue backs up at three times its normal rate. Walters repeats that the notice period is sixty days and has not yet been sixty days.`,
 freeze_collision:`Tuesday, 2:00 p.m. An integration defect drops eligibility responses for one payer covering 18 percent of scheduled volume. The repair is a two-line configuration change. Kubiak says the freeze is the freeze: eleven days. Twenty-two percent of volume is now verified by hand by staff eight days into a new way of working. Nothing breaks dramatically. Everything degrades.`,
 restatement:`Thursday, 3:00 p.m. The board finance committee requests a component reconciliation of the $3.1 million before the meeting. You have eight days. Of the amount, $1.9 million is real, $0.8 million is avoidance against an unrevalidated forecast, and $0.4 million belongs to a payer renegotiation claimed by two projects. Annual RPA license and maintenance of roughly $0.6 million was never netted. Okonkwo calls at 6:40 and asks for the number. After a pause he says, "That's not what I told them."`,
 clinical_revolt:`Thursday, 5:30 p.m. The medical staff meeting runs long. The documentation assistant has been live eleven days. In testing it saved four minutes per encounter; in production physicians read every draft carefully because they sign it, and that takes longer than writing did. Priya Anand stands and says she supported the project, told her colleagues it would help, and was wrong. Moreau formally suspends the documentation component pending review over attestation.`,
 vendor_cliff:`Tuesday. The month-two SLA report arrives eleven days late. Denials inventory has grown 40 percent and aged accounts over 90 days are up 61 percent. Staffing is at plan, but the exception categories consuming the work were never specified in the SLA. The contract offers only termination with 90 days' notice, with no service credit or step-in right. Termination would mean reabsorbing 140 FTE of work into an organization that no longer has them.`
};

const rounds:Record<RoundNumber,RoundContent>={
 1:{base:`Your badge works. That is the first thing you find out at Regional Health Partners at 7:20 on Monday morning. Your fourth-floor office is two doors down from Doug Vandermeer's old office; his whiteboard still carries an eleven-week-old burndown chart with three items open. Okonkwo's four-sentence Sunday message asks for a thirty-day plan by Friday and mentions that the fiscal year closes in seven months. Four executive meetings are already on your calendar. Walters has also written to remind you that Article 14 requires sixty days' written notice before a material job-classification change. Project Clearpath is fourteen months old, with $6.2 million spent against a $9 million budget. Its eligibility pilot covers roughly thirty percent of scheduled outpatient volume. Doug's last report was green. Doug left six weeks ago. The shared folder CLEARPATH_ALL says it contains sixty-three documents.`},
 2:{base:`The thirty-day plan went to Okonkwo Friday. He answered Saturday with two words and a period. Four conversations happened last week and none agreed. Deiss focused on 4.2 percent cost to collect against 2.8, and asked what your baseline was. Moreau gave you eleven minutes and asked whether this would add clicks. Ntende answered every question and volunteered nothing. Kubiak mentioned the Epic change freeze once, inside a longer sentence. The denial rate remains 11.4 percent. This week you have the calendar, the budget, and until Friday to find out what happens between scheduling and claim submission.`},
 3:{base:`Three things arrive before nine Monday. Brennan asks whether you have a baseline and what it is measured against. Okonkwo forwards a board finance committee invitation seven weeks out. Deiss turns Doug's deck to slide 14: $3.1 million realized. Two quarters ago the committee asked for a reconciliation; it never received one. By Friday you owe a read on where the process is constrained and a number, or a decision not to give one.`,variants:[
   {id:'r3-observation-thread',conditionId:'r2_floor_observation_funded',matches:(_,s)=>Number((prior(s,2,'discovery_allocation') as Record<string,number>|undefined)?.floor_observation??0)>0,text:`At the west campus registration desk, Marisol Ferrara opens a drawer. A laminated card taped inside has two columns of payer names and plan codes. She closes it without comment.`},
   {id:'r3-mining-thread',conditionId:'r2_process_mining_funded',matches:(_,s)=>Number((prior(s,2,'discovery_allocation') as Record<string,number>|undefined)?.process_mining??0)>0,text:`The authorization workqueue extract is clean. Its queue-depth chart has no sawtooth. It has a slope, and has had one for twenty-two months.`}
  ],defaultId:'r3-document-discrepancy',defaultText:`The Clearpath map shows eleven steps between scheduling and claim submission. The workqueue configuration shows nineteen. Nobody has reconciled them.`},
 4:{base:`The analysis is done. Thursday's findings readout puts nine people in one room, seven of whom own part of what you will describe. Sylvia closes your door Monday and says, "I'd like to know what you're going to say Thursday before you say it." Twelve months of denials point across functions: roughly 34 percent eligibility and coverage data, 27 percent authorization gaps, 21 percent clinical documentation timing, and 18 percent elsewhere. The finding is a cross-functional problem with four owners and no owner.`,variants:[
   {id:'r4-deep-composition',conditionId:'discovery_supports_root_cause_composition',matches:s=>(s.scalars.discovery_depth??0)>=50,text:`The composition is available by operational cause. Within the 34 percent eligibility category, weekend staleness, distrust-driven re-keying, and other causes separate cleanly enough to discuss.`}
  ],defaultId:'r4-official-categorization',defaultText:`The official categorization sorts by payer and denial code. It does not establish operational cause.`},
 5:{base:`Five weeks remain. Okonkwo writes, "Good readout Thursday. Now let's see the answer." Three days of working sessions will define the replacement, and whoever occupies the twelve chairs will describe the future everyone else receives. Walters asks to be included while options are still open. Moreau can give one hour. Sylvia asks whether she is designing or being designed for. The choices range from refinement, through front-end redesign, to clean-sheet consolidation. Article 14 and the Week 8 go-live date are both already in the record.`,variants:[
   {id:'r5-sylvia-disclosure',conditionId:'r4_systemic_readout_and_ntende_trust',matches:(s,subs)=>((prior(subs,4,'root_cause_claim') as Record<string,unknown>|undefined)?.framing==='system_condition')&&s.stakeholders.ntende.trust>=65,text:`After the readout, Sylvia tells you that she flagged a double-counted component in Doug's $3.1 million, showed him the queue in month four, and was told the vendor had already been selected. Then she says she applied for your job. "I'd have done it differently and I don't know that I'd have done it better."`}
  ],defaultId:'r5-professional-distance',defaultText:`The readout closes without an additional private disclosure from Sylvia.`},
 6:{base:`The vendor arrives Tuesday with a polished fifteen-slide deck. Their architect is competent, answers directly, and says exception handling is what breaks. The smallest reference client shows eleven million. Okonkwo says afterward, "That's the first thing I've seen since you got here that gets us to the number." Oyelaran watches the recording, says the platform and timeline are sound, then asks for an hour to answer five questions about thresholds, change detection, exception ownership, rollback, and patient escalation.`,variants:[
   {id:'r6-it-in-room',conditionId:'r5_it_in_design_room',matches:(_,s)=>has(s,5,'design_room','it'),text:`Kubiak says the Option B work lands inside the freeze, but he can find four days in its second week if he knows now. Option C needs an integration pattern his team has never supported.`},
   {id:'r6-clinical-path-open',conditionId:'r5_physicians_in_design_room',matches:(_,s)=>has(s,5,'design_room','physicians'),text:`Moreau will discuss Option D on a narrow path: one service line, with Anand seeing it before the medical staff.`}
  ],defaultId:'r6-room-silent',defaultText:`No one supplies hidden calendar slack or a narrow clinical path. The advertised build dates remain unchanged.`},
 7:{base:`Castellanos sends a fourteen-page readiness assessment Monday night with no summary. Forty-one interviews cover six functions and two campuses. West staff can describe the new work. East staff largely cannot; three believe the project was cancelled. Nobody was hostile. "Hostility would be easier." Okonkwo writes that the board meeting is three weeks out and assumes go-live remains the 14th. There is $1.4 million left to divide between readiness and contingency.`},
 8:{base:`Sunday night. Cutover begins at 6:00 Monday if it happens. Technical readiness is green. Process readiness is green. Staff readiness is amber. A fourth indicator carries what prior decisions left unresolved. Okonkwo has called twice to ask whether you need anything. Sylvia is in the building though she did not have to be.`,variants:[
   {id:'r8-exception-unvalidated',conditionId:'automation_risk_debt_high',matches:s=>(s.scalars.automation_risk_debt??0)>=55,text:`Exception handling — unvalidated. Projected volume at go-live is 340 to 900 per day; the range is wide because the rules have not run against production data.`},
   {id:'r8-change-window-constrained',conditionId:'technical_partnership_low',matches:s=>(s.scalars.technical_partnership??0)<35,text:`Change window — constrained. Any defect found after 6:00 Monday waits eleven days for a patch.`},
   {id:'r8-workforce-notice',conditionId:'clean_sheet_notice_incomplete',matches:(_,s)=>prior(s,5,'redesign_ambition')==='clean_sheet'&&!has(s,5,'design_room','union'),text:`Workforce — notice period incomplete. Legal has flagged it. Nobody has said what happens if you proceed.`},
   {id:'r8-process-variance',conditionId:'discovery_shallow',matches:s=>(s.scalars.discovery_depth??0)<50,text:`Process variance — undocumented. Four east-campus workflows do not match the documented process and were found Friday.`},
   {id:'r8-vendor-transition',conditionId:'external_sourcing',matches:(_,s)=>prior(s,6,'sourcing')!=='retain_internal',text:`Vendor transition — month one. The BPO has staffed to plan and has not yet run a full day of volume.`}
  ],defaultId:'r8-controlled-opening',defaultText:`The fourth indicator records no additional exception beyond the three visible readiness dimensions.`},
 9:{base:`Attention is finite. Three decisions attach to each crisis: what you do, what you say and to whom, and whether you pull the affected work back.`,variants:(Object.keys(crisisText) as RiskId[]).map(id=>({id:`r9-${id}`,conditionId:`crisis_${id}_selected`,matches:s=>s.crises.some(x=>x.id===id),text:crisisText[id]})),defaultId:'r9-benefit-review',defaultText:`The board finance committee moves its benefit realization review forward by three weeks. You have five days. The process is nine days old; the numbers are real and thin. Registration time is down and the authorization queue has stopped growing, which is not the same as shrinking. Nothing is on fire. You must explain why something that is working is not yet finished.`},
 10:{base:`The board finance committee meets Thursday at 2:00. Project charge codes close at month-end, finance's analysts return, and vendor implementation staffing falls from eleven people to two. Registration time is down; the authorization queue has begun, slightly, to shrink. Cost to collect will not move measurably for two quarters. Okonkwo asks to align on Thursday. Sylvia schedules a ninety-minute Friday transition with a printed agenda.`,variants:[
   {id:'r10-real-ownership',conditionId:'ntende_real_owner',matches:(state,s)=>(prior(s,5,'process_ownership')==='ntende'||prior(s,5,'process_ownership')==='new_role')&&state.stakeholders.ntende.trust>=50,text:`Sylvia says her first action is to remove the 2023 write-ups because the reps have carried them for two years and nobody on the project opened an HR file. She says it as a to-do, not a rebuke.`},
   {id:'r10-nominal-ownership',conditionId:'committee_or_unassigned_owner',matches:(_,s)=>['committee','unassigned'].includes(String(prior(s,5,'process_ownership'))),text:`Sylvia asks who she calls when something needs deciding. She waits. There is no good answer.`},
   {id:'r10-relationship-distant',conditionId:'ntende_relationship_never_turned',matches:(state,s)=>!['committee','unassigned'].includes(String(prior(s,5,'process_ownership')))&&!((prior(s,5,'process_ownership')==='ntende'||prior(s,5,'process_ownership')==='new_role')&&state.stakeholders.ntende.trust>=50),text:`The handoff is competent, complete, and professional. Sylvia volunteers nothing. At the end she says, "Thank you for your time."`}
  ],defaultId:'r10-transition',defaultText:`Sylvia walks through what she is taking on, what remains unclear, and what she expects to break first.`}
};

export function selectRoundNarrative(round:RoundNumber,state:TeamState,submissions:RoundSubmission[],_config:BpmConfig):RoundNarrativeSnapshot{
 void _config;
 const spec=rounds[round],conditions=(spec.variants??[]).map(v=>({conditionId:v.conditionId,matched:v.matches(state,submissions)}));
 const fired=(spec.variants??[]).filter((_,index)=>conditions[index].matched);
 if(round===8&&fired.length){const selected=fired[0],count=fired.length-1;return {round,variantId:selected.id,conditionResults:conditions,renderedContent:[spec.base,selected.text,count?`Plus ${count} other${count===1?'':'s'}.`:undefined].filter(Boolean).join('\n\n')};}
 const variantId=fired.length?fired.map(v=>v.id).join('+'):(spec.defaultId??`r${round}-base`);
 const additions=fired.length?fired.map(v=>v.text):(spec.defaultText?[spec.defaultText]:[]);
 return {round,variantId,conditionResults:conditions,renderedContent:[spec.base,...additions].join('\n\n')};
}

export function narrativeCatalog(){return rounds;}
