import {z} from 'zod';import type {BpmConfig,RoundNumber} from './types.js';
const uniqueSet=(values:readonly string[])=>z.array(z.enum(values as [string,...string[]])).refine(v=>new Set(v).size===v.length,'Duplicates are not allowed');
const allocation=(keys:string[])=>z.record(z.string(),z.number().nonnegative()).superRefine((v,ctx)=>{if(keys.some(k=>v[k]===undefined))ctx.addIssue({code:'custom',message:'All allocation keys are required'});});
const parameter=z.object({threshold_usd:z.number().nonnegative().nullable(),threshold_owner:z.string().nullable(),change_detection:z.string().nullable(),queue_owner_and_authority:z.string().nullable(),rollback_trigger:z.object({threshold:z.number().nonnegative(),authority:z.string().min(1)}).nullable(),patient_escalation_path:z.string().nullable()}).strict();
const metric=z.object({id:z.string().min(1),label:z.string().min(1),category:z.string().min(1),unit:z.string().min(1),baselineValue:z.number().nullable().optional(),targetValue:z.number().nullable().optional()});
export function attentionCost(responses:Record<string,{containment:string;disclosure:string;rollback:boolean}>,rollbackFunded:boolean,c:BpmConfig){return Object.values(responses).reduce((n,r)=>n+(c.attention.containment[r.containment]??0)+(c.attention.disclosure[r.disclosure]??0)+(r.rollback?(rollbackFunded?c.attention.rollback.funded:c.attention.rollback.unfunded):0),0);}
export function submissionSchema(round:RoundNumber,c:BpmConfig,context:{remainingBudget?:number;crisisIds?:string[];rollbackFunded?:boolean}={}){const remaining=context.remainingBudget??c.budget.initialRemainingUsd;const schemas:Record<RoundNumber,z.ZodTypeAny>={
1:z.object({opening_posture:z.enum(['continue_clearpath','pause_pilot','restart_discovery','terminate_pilot']),savings_commitment_made:z.boolean(),savings_commitment_usd:z.number().nonnegative().nullable(),memo_handling:z.enum(['not_found','found_suppressed','raised_okonkwo','raised_deiss','surfaced_public'])}).superRefine((v,x)=>{if(v.savings_commitment_made&&v.savings_commitment_usd===null)x.addIssue({code:'custom',path:['savings_commitment_usd'],message:'Amount is required'});if(!v.savings_commitment_made&&v.savings_commitment_usd!==null)x.addIssue({code:'custom',path:['savings_commitment_usd'],message:'Amount must be null'});}),
2:z.object({discovery_allocation:allocation(Object.keys(c.discovery.yields)).refine(v=>Object.values(v).reduce((a,b)=>a+b,0)===100,'Allocation must total 100'),discovery_scope:z.enum(['denials_only','denials_through_auth','full_front_end'])}),
3:z.object({constraint_claim:z.object({station:z.enum(c.stations as [string,...string[]]),shortfall_estimate:z.number().int(),implication_text:z.string().min(1)}),published_baseline:z.enum(['adopt_inherited','restate_documented','publish_range','defer']),artifact:z.object({bottleneckMap:z.object({stations:z.array(z.object({station:z.enum(c.stations as [string,...string[]]),input:z.number().nullable().optional(),capacity:z.number().nullable().optional(),output:z.number().nullable().optional()})).min(1)}),metricSet:z.array(metric).min(1)})}),
4:z.object({root_cause_claim:z.object({primary_component:z.enum(['eligibility_front_end_data','authorization_workflow','clinical_documentation_timing','other']),secondary_component:z.enum(['eligibility_front_end_data','authorization_workflow','clinical_documentation_timing','other']),weights:z.tuple([z.number().int().nonnegative(),z.number().int().nonnegative()]).refine(v=>v[0]+v[1]<=100),framing:z.enum(['function','system_condition','named_individual'])})}),
5:z.object({redesign_ambition:z.enum(['refine','redesign_structure_intact','clean_sheet']),design_room:uniqueSet(['frontline_staff','union','physicians','it']),process_ownership:z.enum(['unassigned','ntende','new_role','committee','it'])}),
6:z.object({automation_depth:z.enum(['A','B','C','D']),automates_authorization:z.boolean(),sourcing:z.enum(['retain_internal','cosource_denials','full_bpo']),parameter_set:parameter}),
7:z.object({implementation_approach:z.enum(['pilot_single_site','phase_by_function','system_wide']),coalition_actions:uniqueSet(['anand_concrete_commitment','walters_negotiated_path','moreau_advance_brief','ntende_public_ownership']),budget_allocation:z.object({training:z.number().nonnegative(),contingency_reserve:z.number().nonnegative()}).refine(v=>v.training+v.contingency_reserve===remaining,'Allocation must equal current remaining budget')}),
8:z.object({go_decision:z.boolean(),cutover_controls:uniqueSet(['command_center','parallel_running','manual_fallback','rollback_capability'])}).superRefine((v,x)=>{const spend=v.cutover_controls.reduce((n,k)=>n+c.budget.controlCosts[k],0);if(spend>remaining)x.addIssue({code:'custom',path:['cutover_controls'],message:`Controls cost ${spend}, above remaining budget ${remaining}`});}),
9:(context.crisisIds?.length?z.object({crisis_responses:z.record(z.string(),z.object({containment:z.enum(['let_run','contain_narrow','contain_broad','halt_process']),disclosure:z.enum(['none','okonkwo_only','executive_team','board_proactive','public']),rollback:z.boolean()}))}).superRefine((v,x)=>{const expected=context.crisisIds??[];if(expected.some(id=>!v.crisis_responses[id]))x.addIssue({code:'custom',message:'Every active crisis requires a response'});const cost=attentionCost(v.crisis_responses,context.rollbackFunded??false,c);if(cost>c.attention.total)x.addIssue({code:'custom',message:`Requested actions use ${cost}/${c.attention.total} attention. Reduce the response.`});}):z.object({presented_figure:z.object({figure_type:z.enum(['defensible_today','projected_run_rate','range_with_assumptions','decline_to_quantify']),figure_usd:z.number().nonnegative().nullable(),basis_text:z.string().min(1)}).superRefine((v,x)=>{if(v.figure_type!=='decline_to_quantify'&&v.figure_usd===null)x.addIssue({code:'custom',path:['figure_usd'],message:'Please enter a figure before submitting.'});if(v.figure_type==='decline_to_quantify'&&v.figure_usd!==null)x.addIssue({code:'custom',path:['figure_usd'],message:'Leave the figure blank when declining to quantify.'});}),disclosure_items:uniqueSet(['nine_days_of_data','queue_stopped_growing_not_shrinking','cost_to_collect_lags_two_quarters','denial_rate_still_noisy'])})),
10:z.object({sustainment:uniqueSet(['named_process_owner','monitoring_metrics','exception_review_cadence','change_governance']),metric_strategy:z.enum(['inherit','rebuild']),board_narrative:z.object({claimed_benefit_usd:z.number().nonnegative(),disclosure_items:uniqueSet(['crisis_occurred','assumptions_stated','not_yet_working','two_quarter_lag']),figure_change_explained:z.boolean().optional(),figure_explanation:z.string().optional()}),vendor_governance:uniqueSet(['sla_operational_remedies','step_in_rights','process_ownership_named']).optional()}).superRefine((v,x)=>{const spend=v.sustainment.reduce((n,k)=>n+c.budget.sustainmentCosts[k],0)+(v.metric_strategy==='rebuild'?c.budget.metricRebuildCost:0);if(spend>remaining)x.addIssue({code:'custom',message:`Sustainment costs ${spend}, above remaining budget ${remaining}`});})};return schemas[round];}
const placeholder=/^(?:\s*|t\.?b\.?d\.?|unknown|later|n\/?a|none)$/i;export const isSemanticNull=(value:unknown):boolean=>value===null||value===undefined||(typeof value==='string'&&placeholder.test(value.trim()));
