export type RoundNumber = 1|2|3|4|5|6|7|8|9|10;
export type ScalarKey = 'sponsor_confidence'|'board_credibility'|'financial_credibility'|'discovery_depth'|'readiness'|'automation_risk_debt'|'technical_partnership'|'realized_benefit_usd'|'defensible_benefit_usd';
export type ScalarState = Record<ScalarKey,number|null>;
export type StakeholderId = 'ntende'|'deiss'|'moreau'|'kubiak'|'anand'|'walters'|'ferrara'|'boyce'|'reyes';
export type AdvisorId = 'marchetti'|'oyelaran'|'castellanos'|'brennan'|'kowalczyk'|'okonkwo';
export type RiskId = 'statement_4_17'|'duplicate_posting'|'silent_field_change'|'grievance'|'freeze_collision'|'restatement'|'clinical_revolt'|'vendor_cliff';
export type AdvisorValence = 'support'|'mixed'|'oppose';
export interface StateDelta {round:RoundNumber;source:string;field:string;previous:number|null;rawDelta:number;appliedDelta:number;result:number|null}
export interface RiskContribution {sourceRound:RoundNumber;sourceRule:string;points:number;automationDerived:boolean}
export interface RiskState {id:RiskId;exposure:number;contributions:RiskContribution[];eligible:boolean;selected:boolean;severity:number|null}
export interface EvidenceState {id:string;available:boolean;discovered:boolean;accessed:boolean;accessedVersions?:string[];accessedPages?:number[]}
export interface AdvisorStance {advisor:AdvisorId;valence:AdvisorValence;intensity:number;rationale_tags:string[];focus_lever:string|null;components:Record<string,number>;renderContext?:Record<string,unknown>}
export interface BudgetEntry {round:RoundNumber;item:string;amount:number;remainingBalance:number}
export interface CrisisInstance {id:RiskId;severity:number;fullyContained?:boolean;damageMultiplier?:number}
export interface TeamState {scalars:ScalarState;stakeholders:Record<StakeholderId,{trust:number;position:number}>;risks:Record<RiskId,RiskState>;evidence:Record<string,EvidenceState>;budget:{initial:number;spent:number;remaining:number;ledger:BudgetEntry[]};readinessIndicators?:Array<{id:string;status:string;label:string;consequenceRange?:string;additionalCount?:number}>;crises:CrisisInstance[];implementation?:{approach:string;startDate:string;plannedEndDate:string;actualEndDate:string;delayDays:number};outcome?:string;round:RoundNumber|0}
export interface SubmissionCorrection {gameId:string;teamId:string;round:RoundNumber;action:'instructor_correction';actor:'instructor';timestamp:string;changes:Array<{field:string;oldValue:unknown;newValue:unknown}>}
/** kind=non_submission records absence; payload holds only genuine passive resolution values, never authored work. */
export interface RoundSubmission {id:string;gameId:string;teamId:string;round:RoundNumber;payload:Record<string,unknown>;submitter:string;submittedAt:string;configVersion:string;configHash:string;kind?:'non_submission';corrections?:SubmissionCorrection[]}
export interface RoundResult {round:RoundNumber;stateDeltas:StateDelta[];stakeholderEffects:StateDelta[];advisorStances:AdvisorStance[];riskUpdates:Partial<Record<RiskId,RiskState>>;derived:Record<string,unknown>;narrativeVariants:string[];narrativeSnapshot?:RoundNarrativeSnapshot;hiddenScores:Record<string,unknown>;selectedCrises:RiskId[]}
export interface NarrativeConditionResult {conditionId:string;matched:boolean}
export interface RoundNarrativeSnapshot {round:RoundNumber;variantId:string;conditionResults:NarrativeConditionResult[];renderedContent:string}
export interface Transcript {id:string;gameId:string;teamId:string;round:RoundNumber;actorType:'advisor'|'stakeholder';actorId:string;userMessage:string;actorReply:string;timestamp:string;contextHash:string}
export interface MetricDefinition {id:string;label:string;category:string;unit:string;baselineValue?:number|null;targetValue?:number|null}
export interface Round3ArtifactContent {bottleneckMap:{stations:Array<{station:string;input?:number|null;capacity?:number|null;output?:number|null}>};metricSet:MetricDefinition[]}
export interface ArtifactVersion {id:string;label:string;isDefault:boolean;content:Record<string,unknown>}
export interface ArtifactPage {page:number;title?:string;content:string}
export interface Artifact {id:string;title?:string;round:RoundNumber;type:string;versions?:ArtifactVersion[];pages?:ArtifactPage[];content?:Record<string,unknown>;accessRules?:Record<string,unknown>;metadata?:Record<string,unknown>;studentContent:Record<string,unknown>;hiddenMetadata:Record<string,unknown>}
export interface Team {id:string;name:string;accessCode?:string;members:string[];submissions:RoundSubmission[];results:RoundResult[];roundNarratives:RoundNarrativeSnapshot[];currentState:TeamState;stateHistory:TeamState[];transcripts:Transcript[];artifacts:Artifact[]}
export interface Game {id:string;simulationId:'the_reengineering_mandate';configVersion:'bpm-v1';configHash:string;configSnapshot:BpmConfig;teams:Team[];activeRound:RoundNumber;createdAt:string;status:'created'|'active'|'completed'}
export interface CrisisDamage {scalars?:Partial<Record<ScalarKey,number>>;stakeholders?:Partial<Record<StakeholderId,{trust?:number;position?:number}>>;benefitUsd:number;delayDays?:number}
export interface BpmConfig {
 version:'bpm-v1';scenarioVersion:string;unresolved:Record<string,string>;scalar:Record<ScalarKey,{init:number|null;drift:number;min:number;max:number|null}>;stakeholders:Record<StakeholderId,{trust:number;position:number}>;disclosureGates:Record<string,unknown>;stations:string[];
 discovery:{yields:Record<string,number>;scopeMultipliers:Record<string,number>;scopeCoverage:Record<string,number>};readiness:{weights:{designQuality:number;executorPosition:number;frontline:number;training:number};trainingFullCreditUsd:number;discoveryMultiplier:{min:number;max:number;interpolation:'linear'}};automationMultipliers:Record<string,number>;automationDebt:{inherited:number;missing:{thresholdGovernance:number;changeDetection:number;queueOwnership:number;rollbackTrigger:number;patientEscalation:number}};
 budget:{initialRemainingUsd:number;controlCosts:Record<string,number>;sustainmentCosts:Record<string,number>;metricRebuildCost:number;unfundedRollbackCost:number};risks:{selection:{first:number;second:number};canonicalOrder:RiskId[];financialCredibilityBands:Array<{min:number;points:number}>;authorizationAutomation:Record<string,number>;sourcingMultiplier:Record<string,number>;restatement:{commitmentGapFullScaleUsd:number;supportedBenefitCell:{ambition:string;depth:string}}};
 benefits:{baseMatrix:Record<string,Record<string,number>>;readinessFactor:{min:number;max:number};crisisDamage:Record<RiskId,CrisisDamage>;credibilityFactor:{financialWeight:number;boardWeight:number;minimum:number;baselineMethod:Record<string,number>};sustainmentRetention:[number,number,number,number,number];triumphSeverityThreshold:number;materialRelationshipDamage:number;substantialDefensibilityRatio:number};
 advisors:{coefficients:Record<AdvisorId,Record<string,number>>;bands:{strongSupport:number;support:number;oppose:number;strongOppose:number};oyelaranInteractionPenalty:number;kowalczykLowDiscoveryMultiplier:number;okonkwoLowConfidenceMultiplier:number;okonkwoHighConfidenceMultiplier:number;operationalFacts:Array<{id:string;description:string;addressedBy:string;discoveryPath:string}>};attention:{total:number;containment:Record<string,number>;disclosure:Record<string,number>;rollback:{funded:number;unfunded:number}};crisisResponse:{containmentMultiplier:Record<string,number>;rollbackMultiplier:{funded:number;unfunded:number};disclosureCredibilityMultiplier:Record<string,number>};durations:Record<string,number>;calendar:{implementationStart:string;unionNoticeDays:number;epicFreezeStart:string;fiscalYearDeadline:string};claimScoring:{constraintWeights:{location:number;arithmetic:number;implication:number};rootCauseWeights:{component:number;proportionality:number};benefitReviewWeights:{disclosure:number;basis:number;type:number}};benefitReview:{lowerBasisBands?:{substantialMaxRatio:number;peakMinRatio:number;substantialScore:number;lowScore:number};figureChangeThresholdPercent:number;unexplainedChangeBoardCredibilityPenalty:number};
}
