import {useRef,useState} from 'react';
import {api,type CreatedSession} from '../api.js';

export function CreateSimulationSession({token,onOpen}:{token:string;onOpen:(gameId:string)=>Promise<void>}){
 const [count,setCount]=useState('12'),[created,setCreated]=useState<CreatedSession|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[copied,setCopied]=useState(false);
 const pending=useRef(false);
 const details=created?['The Reengineering Mandate',`Game ID: ${created.gameId}`,...created.teams.map(t=>`${t.name} — Code: ${t.code}`)].join('\n'):'';
 return <main className="entry"><section className="card entry-card"><p className="eyebrow">INSTRUCTOR</p><h1>{created?'Session Created Successfully':'Create Simulation Session'}</h1>
 {created?<><p>Game ID: <strong>{created.gameId}</strong></p><ul>{created.teams.map(t=><li key={t.name}><strong>{t.name}</strong> — Code: <code>{t.code}</code></li>)}</ul><button onClick={async()=>{setError('');setCopied(false);try{await navigator.clipboard.writeText(details);setCopied(true);}catch{setError('Copy is unavailable. Select and copy the access details below.');}}}>Copy Student Access Details</button>{copied?<p role="status">Student access details copied.</p>:null}<label>Student access details<textarea readOnly rows={6} value={details}/></label><button className="primary" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await onOpen(created.gameId);}catch{setError('Unable to open the control room. Use the Game ID in the existing game selector.');}finally{setBusy(false);}}}>Open Instructor Control Room</button></>:<form onSubmit={async e=>{e.preventDefault();if(pending.current)return;const teams=Number(count);if(!count.trim()||!Number.isInteger(teams)||teams<1||teams>12){setError('Number of teams must be a whole number from 1 to 12.');return;}pending.current=true;setBusy(true);setError('');try{setCreated(await api.createSession(teams,token));}catch(e){setError(`${e instanceof Error?e.message:'Unable to create session.'} If the connection was interrupted, check the existing game selector before creating another session.`);}finally{pending.current=false;setBusy(false);}}}><p>Simulation: The Reengineering Mandate</p><label>Number of Teams<input type="number" min={1} max={12} step={1} required value={count} disabled={busy} onChange={e=>setCount(e.target.value)}/></label><button className="primary" disabled={busy}>{busy?'Creating…':'Create Session'}</button></form>}
 {error?<p className="error" role="alert">{error}</p>:null}<p><a href="?view=instructor">Select an existing game</a></p></section></main>;
}
