import {writeFileSync} from 'node:fs';
import {scoreAdvisors} from '../src/domain/advisors.js';
import {cloneConfig} from '../src/domain/config.js';
import {DeterministicConversationProvider} from '../src/domain/conversations.js';
import {initialState} from '../src/domain/engine.js';
import type {AdvisorId,RoundNumber} from '../src/domain/types.js';
const c=cloneConfig(),provider=new DeterministicConversationProvider();
const base:Record<number,Record<string,unknown>>={1:{opening_posture:'pause_pilot',savings_commitment_made:true,savings_commitment_usd:8000000,memo_handling:'raised_deiss'},2:{discovery_allocation:{document_analysis:5,structured_interviews:25,process_mining:30,floor_observation:40},discovery_scope:'full_front_end'},3:{constraint_claim:{station:'authorization',shortfall_estimate:91,implication_text:'Observed upstream work changed pressure in a downstream queue.'},published_baseline:'restate_documented'},4:{root_cause_claim:{primary_component:'eligibility_front_end_data',secondary_component:'authorization_workflow',weights:[34,27],framing:'system_condition'}},5:{redesign_ambition:'clean_sheet',design_room:['frontline_staff','union','physicians','it'],process_ownership:'ntende'},6:{automation_depth:'D',automates_authorization:true,sourcing:'retain_internal',parameter_set:{threshold_usd:10,threshold_owner:'CFO',change_detection:'version monitor',queue_owner_and_authority:'director may halt',rollback_trigger:{threshold:10,authority:'CIO'},patient_escalation_path:'patient advocate'}},7:{implementation_approach:'phase_by_function',coalition_actions:['anand_concrete_commitment','walters_negotiated_path','moreau_advance_brief','ntende_public_ownership'],budget_allocation:{training:700000,contingency_reserve:0}},8:{go_decision:true,cutover_controls:['command_center','parallel_running','manual_fallback','rollback_capability']},9:{crisis_responses:{restatement:{containment:'contain_broad',disclosure:'executive_team',rollback:false}}},10:{sustainment:['named_process_owner','monitoring_metrics','exception_review_cadence','change_governance'],metric_strategy:'inherit',board_narrative:{claimed_benefit_usd:8000000,disclosure_items:['assumptions_stated']}}};
const scenarios=['disciplined team','weak discovery','aggressive automation','poor stakeholder engagement','strong evidence path','inherited baseline path','crisis path'] as const;
function build(name:typeof scenarios[number]){const state=initialState(c),ps=structuredClone(base);state.scalars.discovery_depth=name==='weak discovery'?25:name==='strong evidence path'?95:75;state.scalars.readiness=82;if(name==='disciplined team')ps[7]={...ps[7],implementation_approach:'system_wide'};if(name==='aggressive automation')ps[6]={...ps[6],automation_depth:'D',parameter_set:{threshold_usd:null,threshold_owner:'TBD',change_detection:'',queue_owner_and_authority:'placeholder',rollback_trigger:null,patient_escalation_path:null}};if(name==='poor stakeholder engagement'){for(const id of ['walters','ferrara','boyce','ntende'] as const)state.stakeholders[id].position=0;ps[2]={discovery_allocation:{document_analysis:0,structured_interviews:0,process_mining:0,floor_observation:100},discovery_scope:'denials_only'};ps[5]={...ps[5],design_room:['frontline_staff','union'],process_ownership:'ntende'};ps[7]={...ps[7],implementation_approach:'system_wide',coalition_actions:['walters_negotiated_path','ntende_public_ownership'],budget_allocation:{training:0,contingency_reserve:0}}}if(name==='inherited baseline path')ps[3]={...ps[3],published_baseline:'adopt_inherited'};if(name==='crisis path'){state.crises=[{id:'restatement',severity:70}];ps[9]={crisis_responses:{restatement:{containment:'contain_narrow',disclosure:'none',rollback:false}}}}const subs=Object.entries(ps).map(([round,payload])=>({id:`s${round}`,gameId:'audit',teamId:'team',round:Number(round) as RoundNumber,payload,submitter:'audit',submittedAt:'2026-01-01T00:00:00Z',configVersion:'bpm-v1' as const,configHash:'audit'}));return {state,ps,subs};}
const boundary=(score:number,valence:string,tags:string[])=>tags.includes('phase_it')?`explicit R7 override: phase_it (base ${score.toFixed(3)})`:tags.includes('disclose_faster')?`explicit R9 override: disclose_faster (base ${score.toFixed(3)})`:tags.includes('high_depth_low_parameters')?`explicit interaction override (base ${score.toFixed(3)})`:valence==='support'?`> 0.72 (${score.toFixed(3)})`:valence==='oppose'?`< 0.45 (${score.toFixed(3)})`:`0.45–0.72 (${score.toFixed(3)})`;
const summary=(name:string,round:RoundNumber,x:ReturnType<typeof build>)=>`scenario=${name}; round=${round}; discovery=${x.state.scalars.discovery_depth}; readiness=${x.state.scalars.readiness}; current=${Object.keys(x.ps[round]).join(', ')}`;
const componentText=(values:Record<string,number>)=>Object.entries(values).filter(([k])=>k!=='score'&&!k.toLowerCase().includes('unresolved')).map(([k,v])=>`${k}=${v.toFixed(3)}`).join('; ');
const rows:string[]=[];
for(const advisor of ['marchetti','oyelaran','castellanos','brennan','kowalczyk','okonkwo'] as AdvisorId[])for(let n=1;n<=10;n++)for(const scenario of scenarios){const round=n as RoundNumber,x=build(scenario),stance=scoreAdvisors(round,x.ps[n],x.state,x.subs.filter(s=>s.round<round),c).find(s=>s.advisor===advisor)!,score=stance.components.score??.6,voice=await provider.reply({gameId:'audit',teamId:'team',round,actorType:'advisor',actorId:advisor,message:'Review this decision.',state:x.state,stance});rows.push(`| ${advisor} | R${round} | ${scenario} | ${summary(scenario,round,x)} | ${componentText(stance.components)} | ${score.toFixed(3)} | ${stance.valence} | ${boundary(score,stance.valence,stance.rationale_tags)} | ${stance.intensity.toFixed(2)} | ${stance.rationale_tags.join(', ')} | ${stance.focus_lever??'—'} | ${voice.replaceAll('|','/')} |`);}
const header=`# Advisor Audit — Phase 2\n\nGenerated as the complete advisor × round × scenario cross-product. Component values, weighted scores, tags, and focus levers are internal human-review metadata. Only the rendered voice is student-facing. Sorted by advisor, round, then scenario in the declared representative-scenario order.\n\n| Advisor | Round | Scenario | Input summary | Component values | Weighted score | Valence | Valence boundary crossed | Intensity | Rationale tags | Focus lever | Rendered voice |\n|---|---:|---|---|---|---:|---|---|---:|---|---|---|\n`;
writeFileSync('reports/ADVISOR_AUDIT_PHASE2.md',header+rows.join('\n')+'\n');
