import {writeFileSync} from 'node:fs';
import {cloneConfig} from '../src/domain/config.js';
import {closeRound,createGame,submit} from '../src/domain/engine.js';
import {renderAdvisorMessage} from '../src/domain/conversations.js';
import type {Game,RoundNumber} from '../src/domain/types.js';

const metric={id:'first-pass-clean',label:'First-pass clean rate',category:'quality',unit:'percent',baselineValue:62,targetValue:88};
const artifact={bottleneckMap:{stations:[{station:'verification',input:1840,capacity:2400,output:1840},{station:'authorization',input:610,capacity:519,output:519},{station:'claim_submission',input:1795,capacity:1720,output:1720}]},metricSet:[metric]};
const common={
 1:{opening_posture:'pause_pilot',savings_commitment_made:false,savings_commitment_usd:null,memo_handling:'raised_deiss'},
 3:{constraint_claim:{station:'authorization',shortfall_estimate:91,implication_text:'Verification is upstream; automating it moved pressure into the authorization queue instead of removing the constraint.'},published_baseline:'restate_documented',artifact},
 4:{root_cause_claim:{primary_component:'eligibility_front_end_data',secondary_component:'authorization_workflow',weights:[34,27],framing:'system_condition'}},
} as Record<number,Record<string,unknown>>;
export const paths=[
 {name:'Path A — Disciplined',decisions:{...common,2:{discovery_allocation:{document_analysis:5,structured_interviews:25,process_mining:30,floor_observation:40},discovery_scope:'full_front_end'},5:{redesign_ambition:'redesign_structure_intact',design_room:['frontline_staff','union','physicians','it'],process_ownership:'ntende'},6:{automation_depth:'B',automates_authorization:true,sourcing:'retain_internal',parameter_set:{threshold_usd:25,threshold_owner:'Revenue Cycle Director',change_detection:'Daily portal schema comparison',queue_owner_and_authority:'Revenue Cycle Director; halt authority',rollback_trigger:{threshold:25,authority:'VP Applications'},patient_escalation_path:'Patient advocate escalation'}},7:{implementation_approach:'phase_by_function',coalition_actions:['anand_concrete_commitment','walters_negotiated_path','moreau_advance_brief','ntende_public_ownership'],budget_allocation:{training:700000,contingency_reserve:2100000}},8:{go_decision:true,cutover_controls:['command_center','parallel_running','manual_fallback','rollback_capability']},10:{sustainment:['named_process_owner','monitoring_metrics','exception_review_cadence','change_governance'],metric_strategy:'inherit',board_narrative:{claimed_benefit_usd:7500000,disclosure_items:['assumptions_stated','not_yet_working','two_quarter_lag']}}}},
 {name:'Path B — Automation Risk',decisions:{1:{opening_posture:'continue_clearpath',savings_commitment_made:true,savings_commitment_usd:12000000,memo_handling:'found_suppressed'},2:{discovery_allocation:{document_analysis:100,structured_interviews:0,process_mining:0,floor_observation:0},discovery_scope:'denials_only'},3:{constraint_claim:{station:'claim_submission',shortfall_estimate:75,implication_text:'Submission is where write-offs appear.'},published_baseline:'adopt_inherited',artifact},4:{root_cause_claim:{primary_component:'eligibility_front_end_data',secondary_component:'other',weights:[50,20],framing:'function'}},5:{redesign_ambition:'refine',design_room:[],process_ownership:'committee'},6:{automation_depth:'D',automates_authorization:true,sourcing:'full_bpo',parameter_set:{threshold_usd:null,threshold_owner:null,change_detection:null,queue_owner_and_authority:null,rollback_trigger:null,patient_escalation_path:null}},7:{implementation_approach:'system_wide',coalition_actions:[],budget_allocation:{training:200000,contingency_reserve:2600000}},8:{go_decision:true,cutover_controls:[]},10:{sustainment:['monitoring_metrics'],metric_strategy:'inherit',board_narrative:{claimed_benefit_usd:6000000,disclosure_items:[]},vendor_governance:[]}}},
 {name:'Path C — Option D',decisions:{...common,2:{discovery_allocation:{document_analysis:10,structured_interviews:30,process_mining:30,floor_observation:30},discovery_scope:'full_front_end'},5:{redesign_ambition:'clean_sheet',design_room:['frontline_staff','union','it'],process_ownership:'new_role'},6:{automation_depth:'D',automates_authorization:true,sourcing:'retain_internal',parameter_set:{threshold_usd:25,threshold_owner:'Revenue Cycle Director',change_detection:'Daily portal schema comparison',queue_owner_and_authority:'Revenue Cycle Director; halt authority',rollback_trigger:{threshold:25,authority:'VP Applications'},patient_escalation_path:'Patient advocate escalation'}},7:{implementation_approach:'system_wide',coalition_actions:['walters_negotiated_path','moreau_advance_brief','ntende_public_ownership'],budget_allocation:{training:700000,contingency_reserve:2100000}},8:{go_decision:true,cutover_controls:['command_center','parallel_running','manual_fallback','rollback_capability']},10:{sustainment:['named_process_owner','monitoring_metrics','exception_review_cadence','change_governance'],metric_strategy:'inherit',board_narrative:{claimed_benefit_usd:9000000,disclosure_items:['crisis_occurred','assumptions_stated','not_yet_working','two_quarter_lag']}}}},
 {name:'Path D — Triumph',decisions:{...common,2:{discovery_allocation:{document_analysis:5,structured_interviews:25,process_mining:30,floor_observation:40},discovery_scope:'full_front_end'},5:{redesign_ambition:'clean_sheet',design_room:['frontline_staff','union','physicians','it'],process_ownership:'ntende'},6:{automation_depth:'D',automates_authorization:false,sourcing:'retain_internal',parameter_set:{threshold_usd:1000,threshold_owner:'CFO',change_detection:'Version monitor',queue_owner_and_authority:'Revenue cycle director may halt',rollback_trigger:{threshold:10,authority:'CIO'},patient_escalation_path:'Patient advocate'}},7:{implementation_approach:'phase_by_function',coalition_actions:['anand_concrete_commitment','walters_negotiated_path','moreau_advance_brief','ntende_public_ownership'],budget_allocation:{training:700000,contingency_reserve:2100000}},8:{go_decision:true,cutover_controls:['command_center','parallel_running','manual_fallback','rollback_capability']},10:{sustainment:['named_process_owner','monitoring_metrics','exception_review_cadence','change_governance'],metric_strategy:'inherit',board_narrative:{claimed_benefit_usd:8000000,disclosure_items:['assumptions_stated','two_quarter_lag']}}}}
] as const;

const contacts:Record<string,Record<number,string[]>>={
 'Path A — Disciplined':{2:['Kubiak — Sunday batch disclosed','Ferrara — payer/plan card disclosed','Boyce — root-cause database disclosed'],4:['Ntende answers direct questions; no voluntary disclosure at trust 35'],5:['Walters — five-day clock offer','Moreau — specific Tuesday question'],6:['Kubiak — four-day window','Ntende — contract remedy answer'],7:['Anand — dated commitment','Ntende — public ownership'],8:['Anand — raises project herself'],10:['Ntende — distant professional handoff']},
 'Path B — Automation Risk':{2:['Executive interviews only; no floor disclosures'],4:['Ntende answers only what is asked'],5:['No frontline, union, physician, or IT session disclosures'],7:['No coalition disclosures'],10:['Ntende — nominal ownership handoff']},
 'Path C — Option D':{2:['Ferrara and Boyce discovery','Kubiak process question'],5:['Walters — five-day clock offer'],6:['Kubiak — four-day window','Moreau path not opened before Option D'],7:['Moreau briefed; Anand receives no concrete commitment'],9:['Anand — public apology if clinical revolt selected'],10:['Ntende — distant professional handoff']},
 'Path D — Triumph':{2:['Kubiak — Sunday batch disclosed','Ferrara — payer/plan card disclosed','Boyce — root-cause database disclosed'],5:['Walters and frontline participants included'],6:['All five automation-governance questions answered'],7:['Full coalition activated'],8:['All four cutover controls funded'],9:['No crisis; benefit review'],10:['Ntende — distant professional handoff']}
};

function crisisResponses(crises:Game['teams'][number]['currentState']['crises']){const multiple=crises.length>1;return {crisis_responses:Object.fromEntries(crises.map(x=>[x.id,{containment:multiple?'contain_narrow':'contain_broad',disclosure:'executive_team',rollback:['duplicate_posting','silent_field_change'].includes(x.id)}]))};}
function play(name:string,decisions:Record<number,Record<string,unknown>>){let game=createGame({id:name,teamNames:['Review team'],config:cloneConfig(),createdAt:'2026-09-05T00:00:00Z'});for(let round=1;round<=10;round++){let payload=decisions[round];if(round===9)payload=crisisResponses(game.teams[0].currentState.crises);game=closeRound(submit(game,'team-1',payload,'phase3-review',`2026-09-${String(round).padStart(2,'0')}T12:00:00Z`));}return game;}
function trace(decisions:Record<number,Record<string,unknown>>){let game=createGame({id:'trace',teamNames:['Trace'],config:cloneConfig(),createdAt:'2026-09-05T00:00:00Z'});const trust:number[]=[],depth:number[]=[];for(let round=1;round<=10;round++){let payload=decisions[round];if(round===9)payload=crisisResponses(game.teams[0].currentState.crises);game=closeRound(submit(game,'team-1',payload));trust.push(game.teams[0].currentState.stakeholders.ntende.trust);depth.push(game.teams[0].currentState.scalars.discovery_depth??0);}return {trust,depth};}
function advisors(game:Game,round:RoundNumber){const result=game.teams[0].results.find(x=>x.round===round)!;const selected=result.advisorStances.filter(x=>['marchetti',round>=6&&round<=9?'oyelaran':round>=7?'castellanos':'brennan'].includes(x.advisor)).slice(0,2);return selected.map(x=>`${x.advisor}: “${renderAdvisorMessage(x.advisor,x,round)}”`).join('  \n');}

const runs=paths.map(p=>({name:p.name,game:play(p.name,p.decisions as unknown as Record<number,Record<string,unknown>>)}));
let coverage='# Phase 3 variant coverage\n\nGenerated from four complete deterministic R1–R10 engine runs. Variant IDs and condition results are instructor-review information and are not projected to students.\n\n';
let playthrough='# Phase 3 student-readable playthrough\n\nThe narrative below is the actual rendered content persisted by each complete deterministic run. Internal IDs and conditions are intentionally omitted here.\n\n';
for(const {name,game} of runs){const team=game.teams[0];coverage+=`## ${name}\n\n| Round | Selected variant | Condition | Artifacts available | Stakeholder contacts/disclosures | Advisor conversations | Important consequence |\n|---:|---|---|---|---|---|---|\n`;playthrough+=`## ${name}\n\n`;
 for(let n=1;n<=10;n++){const round=n as RoundNumber,snapshot=team.roundNarratives.find(x=>x.round===round)!,conditions=snapshot.conditionResults.filter(x=>x.matched).map(x=>x.conditionId).join(', ')||'default/base',available=team.artifacts.filter(a=>a.round<=round).map(a=>a.title??a.id).join('; '),contact=(contacts[name]?.[n]??[]).join('; ')||'No additional voluntary disclosure';const consequence=round===9?(team.currentState.crises.map(x=>`${x.id} (${x.severity})`).join(', ')||'benefit review'):round===10?String(team.currentState.outcome):'Narrative fixed at round opening';coverage+=`| ${n} | ${snapshot.variantId} | ${conditions} | ${available} | ${contact} | ${advisors(game,round).replace(/\n/g,' ')} | ${consequence} |\n`;playthrough+=`### R${n}\n\n${snapshot.renderedContent}\n\n**Decision record**  \n\`${JSON.stringify(team.submissions.find(x=>x.round===round)?.payload)}\`\n\n**Conversations heard**  \n${contact}.  \n${advisors(game,round)}\n\n`;}
 playthrough+=`**Final result:** ${team.currentState.outcome}; realized benefit: $${Math.round(team.currentState.scalars.realized_benefit_usd??0).toLocaleString('en-US')}; defensible benefit: $${Math.round(team.currentState.scalars.defensible_benefit_usd??0).toLocaleString('en-US')}; crises fired: ${team.currentState.crises.length}.\n\n`;
 if(name==='Path A — Disciplined')playthrough+=`Path A has no crisis, no materially damaged relationships, and four sustainment items. It therefore has no qualifying scar and falls through to Squeak Through despite defensible benefit above $5 million.\n\n`;
 const allIds=team.roundNarratives.flatMap(x=>x.conditionResults).filter(x=>!x.matched).map(x=>x.conditionId);coverage+=`\nVariants not fired: ${[...new Set(allIds)].join(', ')||'none'}.\n\nOutcome: ${team.currentState.outcome}; realized benefit: $${Math.round(team.currentState.scalars.realized_benefit_usd??0).toLocaleString('en-US')}; defensible benefit: $${Math.round(team.currentState.scalars.defensible_benefit_usd??0).toLocaleString('en-US')}.\n\n`;if(name==='Path A — Disciplined'){const series=trace(paths[0].decisions as unknown as Record<number,Record<string,unknown>>);coverage+=`### Path A revision trace\n\n- R2 allocation: document 5%, interviews 25%, process mining 30%, floor observation 40%.\n- Ntende trust R1–R10: ${series.trust.join(', ')}.\n- Discovery depth R1–R10: ${series.depth.map(x=>x.toFixed(6)).join(', ')}.\n- Final tier: ${team.currentState.outcome}.\n\n`;}}
coverage+=`## Phase 3 revision summary\n\n- Ntende trust has no generic drift; only explicit relationship mechanics move it.\n- R10 Ntende narrative uses one exclusive priority ladder.\n- Discovery uses the authoritative nonlinear 50%-full-weight ramp plus capped R3/R4 recovery.\n- Corrected discovery permits Marchetti support on an evidenced analytical path, with focus- and round-specific voice.\n- Outcome tiers use the authoritative descending ladder: unchanged Triumph first; then Win with Scars at $5M or more, at most one crisis, and a scar from exactly one crisis, at least two materially damaged relationships, or no more than two sustainment items; then positive-benefit/no-restatement Squeak Through; otherwise Disaster. Win with Scars has no upper benefit bound.\n- Path A is Squeak Through because it has no qualifying scar; Path B is Disaster; Path C is Win with Scars; Path D is Triumph.\n`;
writeFileSync('reports/PHASE3_VARIANT_COVERAGE.md',coverage);writeFileSync('reports/PHASE3_PLAYTHROUGH.md',playthrough);
