const base=import.meta.env.VITE_API_BASE??'/api';
async function request<T>(path:string,init?:RequestInit,token?:string):Promise<T>{
 let response:Response;
 try{response=await fetch(`${base}${path}`,{...init,headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{}),...init?.headers}});}
 catch{throw new Error('We could not reach the server. Check your connection and try again.');}
 let data;
 try{data=await response.json();}
 catch{throw new Error('The server could not complete your request. Please try again.');}
 if(!response.ok)throw new Error(data.error??'Your request could not be completed. Please try again.');
 return data;
}
export const api={join:(gameId:string,teamCode:string)=>request<{token:string;gameId:string;teamId:string;teamName:string}>('/student/session',{method:'POST',body:JSON.stringify({gameId,teamCode})}),instructorLogin:(passphrase:string)=>request<{token:string}>('/instructor/session',{method:'POST',body:JSON.stringify({passphrase})}),games:(token:string)=>request<Array<{id:string;status:string;activeRound:number}>>('/games',undefined,token),create:(teamNames:string[],token:string)=>request<InstructorView>('/games',{method:'POST',body:JSON.stringify({teamNames})},token),student:(g:string,t:string,token:string)=>request<StudentView>(`/games/${g}/teams/${t}`,undefined,token),instructor:(g:string,token:string)=>request<InstructorView>(`/games/${g}/instructor`,undefined,token),submit:(g:string,t:string,payload:Record<string,unknown>,token:string)=>request<StudentView>(`/games/${g}/teams/${t}/submissions`,{method:'POST',body:JSON.stringify({payload,submitter:'team member'})},token),close:(g:string,token:string)=>request<InstructorView>(`/games/${g}/close`,{method:'POST'},token),correct:(g:string,t:string,round:number,payload:Record<string,unknown>,token:string)=>request<InstructorView>(`/games/${g}/teams/${t}/submissions/${round}/correction`,{method:'POST',body:JSON.stringify({payload})},token),override:(g:string,round:number,outstandingTeamIds:string[],token:string)=>request<InstructorView>(`/games/${g}/close-with-outstanding`,{method:'POST',body:JSON.stringify({round,outstandingTeamIds,confirmed:true})},token),access:(g:string,t:string,e:string,detail:Record<string,unknown>,token:string)=>request<StudentView>(`/games/${g}/teams/${t}/evidence/${e}/access`,{method:'POST',body:JSON.stringify(detail)},token),chat:(g:string,t:string,body:Record<string,unknown>,token:string)=>request<{actorReply:string}>(`/games/${g}/teams/${t}/conversations`,{method:'POST',body:JSON.stringify(body)},token)};
export interface StudentView {game:{id:string;status:string;activeRound:number};team:{id:string;name:string};situation:string;evidence:Array<{id:string;title:string;accessed:boolean;content?:string}>;artifacts:Array<Record<string,unknown>>;advisors:string[];stakeholders:string[];transcripts:Array<{actorType:string;actorId:string;userMessage:string;actorReply:string;timestamp:string;round?:number}>;decision:{round:number;submitted:boolean;outcome?:string;rollbackReadback?:string;crisisInstances?:Array<{id:string}>;vendorGovernanceOpen?:boolean;remainingBudget?:number;metricSet?:unknown[];priorPresentedFigure?:number|null;readinessIndicators?:Array<{id:string;status:string;label:string;consequenceRange?:string}>};budget:{remaining:number;spent:number;ledger:unknown[]};history:Array<{status?:'NON-SUBMISSION';round:number;payload:Record<string,unknown>;submitter:string;submittedAt:string}>;consequence:unknown;debrief:{outcome?:string;panels:Array<Record<string,unknown>>}|null}
export interface InstructorTranscript {actorType:string;actorId:string;userMessage:string;actorReply:string;timestamp:string;round:number}
export interface InstructorSubmission {id:string;round:number;payload:Record<string,unknown>;submitter:string;submittedAt:string;kind?:'non_submission';corrections?:Array<{timestamp:string;actor:string;action:string;changes:Array<{field:string;oldValue:unknown;newValue:unknown}>}>}
export interface InstructorTeam {id:string;name:string;submissions:InstructorSubmission[];state:Record<string,unknown>;stateHistory:unknown[];results:unknown[];transcripts:InstructorTranscript[];missedEvidence:string[];outcome?:string}
export interface InstructorView {game:{id:string;status:string;activeRound:number;configHash:string};teams:InstructorTeam[];unresolved:Record<string,string>}
